### ISSUE TITLE
Rewrites object format not supported

### ISSUE THREAD

**Issue by myrjola** [serverless-nextjs/serverless-next.js#1003]
### Describe the bug

The rewrites configuration also supports an object, but this does not currently work in the default Lambda. https://nextjs.org/docs/api-reference/next.config.js/rewrites

> Rewrites are applied after checking the filesystem (pages and /public files) and before dynamic routes by default. This behavior can be changed by instead returning an object instead of an array from the rewrites function

### Actual behavior

The default Lambda crashes with the following:

```
{
  "errorType": "TypeError",
  "errorMessage": "rewrites is not iterable",
  "trace": [
    "TypeError: rewrites is not iterable",
    "    at getRewritePath (/var/task/index.js:3461:27)",
    "    at handleOriginRequest (/var/task/index.js:8867:31)",
    "    at Runtime.handler$1 [as handler] (/var/task/index.js:8774:26)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

### Expected behavior

The rewrites should apply without any crash.

### Steps to reproduce

Add rewrites with the object format to next.config.js:

```
module.exports = {
  async rewrites() {
    return {
      beforeFiles: [{
        source: '/fi/varaus',
        destination: '/fi/reservation',
        locale: false
      }]
    }
  },
}
```

When navigating to /fi/varaus, you will get the "rewrites is not iterable" error instead of navigating to the /pages/reservation.tsx page.

### Screenshots/Code/Logs

The crash looks like this from the user's perspective:

![crash image](https://user-images.githubusercontent.com/36122/115050154-20812a00-9ee4-11eb-83bb-e1ea9fde5d47.png)

### Versions

- OS/Environment: Deployed from Gitlab CI/CD pipeline
- @sls-next/serverless-component version: 1.19.0-alpha.42
- Next.js version: 10.1.3

**Comment by dphang** [comment]
Yes it seems Next.js might have recently added rewrites object format? I didn't recall it when I first implemented rewrites. So it would need to be implemented. I'm working on some other stuff at the moment but can tag this as good first issue / enhancement in case someone wants to pick it up.

**Comment by seifeddinebesbes** [comment]
Hello,
I would like to contribute and can i start by take this task ?

**Comment by dphang** [comment]
@seifeddinebesbes Yes! I think no one else is working on it at the moment. Definitely let us know if you need help to get started or you can join the slack as well (email us at serverlessnextjs@gmail.com)

**Comment by seifeddinebesbes** [comment]
@dphang thank you and i already sent you an email :) :) 

Best regards,
Seif

**Comment by zburk** [comment]
Having the same issue. Is there any workaround currently or is downgrading to Next 9 the best option til this is fixed?

**Comment by seifeddinebesbes** [comment]
@zburk  you can use the old rewrites configuration without downgrading to Next9
for example : 
![image](https://user-images.githubusercontent.com/10586765/123657225-e95abd80-d830-11eb-8c4a-3421aaa59ed1.png)

**Comment by zburk** [comment]
Gotcha thanks!

**Comment by MarceloAzeved0** [comment]
Hello, i have the same error, have any updates on this issue?

**Comment by danwestonwunderman** [comment]
This is is still happening. Any news?
