### ISSUE TITLE
Project fails to deploy on Lambda step. No changes to api code or severless config

### ISSUE THREAD

**Issue by jonahallibone** [serverless-nextjs/serverless-next.js#1011]
### Describe the bug
`The role defined for the function cannot be assumed by Lambda.` is being thrown on deployment. 

### Actual behavior
I run `serverless` command and my deploy fails at the lambda step

### Expected behavior
Site should deploy

### Steps to reproduce
Run `serverless`. It happens intermittently, I cannot reliably reproduce it. Have read the solution could be to make the deploy to lambda sleep for a couple seconds after making the role

### Screenshots/Code/Logs
```
error:
971 | InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
972 | at Object.extractError (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/protocol/json.js:52:27)
973 | at Request.extractError (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
974 | at Request.callListeners (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
975 | at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
976 | at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/request.js:688:14)
977 | at Request.transition (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/request.js:22:10)
978 | at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/state_machine.js:14:12)
979 | at /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/state_machine.js:26:10
980 | at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/request.js:38:9)
981 | at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.42/node_modules/aws-sdk/lib/request.js:690:12) {
982 | code: 'InvalidParameterValueException',
983 | time: 2021-04-21T23:37:56.484Z,
984 | requestId: '6ed6092c-e796-4863-90d3-a2af7504e862',
985 | statusCode: 400,
986 | retryable: false,
987 | retryDelay: 38.92080885966563
988 | }
989 | ·[G·[?25h·[G·[J
990 | 335s › privco › InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
991
```

### Versions
OS: Codebuild Linux
Version: alpha.42
NextJS Version 10.1.3

**Comment by dphang** [comment]
Sorry did not get a chance to look at this until now, hopefully it is working now? It sounds like a permission issue or AWS configuration issue, though I haven't see this before myself.

**Comment by jonahallibone** [comment]
@dphang its never happened again since then. I just waited a couple minutes and it's been fine ever since.
