### ISSUE TITLE
Build fails when using serverless, but successful when running next build manually

### ISSUE THREAD

**Issue by DeerajTheepshi** [serverless-nextjs/serverless-next.js#1036]
### Describe the bug
When I run ```next build``` from my project root, the build runs successfully without any errors. However, after this, when I run ```serverlesss``` or ```npx serverless``` the build fails in 30-50s and reports a build error that says ```Build failed because of webpack errors```

### Actual behavior
I'm using nextjs 10.0.2, and I also tried making code changes and downgrading next. Everytime I change the next version, the same thing happens. Manual build passes, but when using serverless, the build fails. However the module/package that is being reported as not found differs for every next version.

Really clueless on what's happening here as manual build fails, however the exact same build command run by serverless fails.

### Expected behavior
Both manual build and build with serverless should pass.
Important thing that I would like to point out is, When I go back in git, to some older version of the project (50-60 commits back), the build works fine manually and with serverless

### Steps to reproduce
Clone the repo,  Run -> ```npm i``` -> , ``` next build ```,->  ``` serverless ```

### Screenshots/Code/Logs
Error Thrown By Serverless

```
Error: Command failed with exit code 1: node_modules/.bin/next build
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'webpack' in '/home/diprivi/testCeleb/nextjs-web-app/node_modules/@next/react-refresh-utils'


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/diprivi/testCeleb/nextjs-web-app/node_modules/next/dist/build/index.js:17:924
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Span.traceAsyncFn (/home/diprivi/testCeleb/nextjs-web-app/node_modules/next/dist/telemetry/trace/trace.js:6:584)
info  - Loaded env from /home/diprivi/testCeleb/nextjs-web-app/.env.production
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
```

### Versions

- OS/Environment: Linux
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.2 / 9.5

### Checklist

- [-] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [-] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Yes it makes sense because experimental serverless trace doesn't use webpack to bundle, it uses their NFT package (node file trace).

I did see some issues where webpack errors in earlier versions of Next.js 10 were fixed later, you could try to upgrade and see if it works properly afterwards.

**Comment by tyler-ground** [comment]
Is there a reason that you don't want to use useServerlessTrace?   You will quickly run out of room in the package without it.
