### ISSUE TITLE
The SSG pages throw an error after revalidation

### ISSUE THREAD

**Issue by ignaciolarranaga** [serverless-nextjs/serverless-next.js#1138]
### Actual behavior
I have a SSG pages deployed to Cloudfront using CDK. The pages are generated correctly the first time, but after the revalidation happen they start failing indicating that a SQS queue is not available (see detail below).

Here is the getStaticProps and getStaticPaths for reference:
```
export async function getStaticProps(context) {
  let localPoll = await ...

  return {
    props: {
      localPoll,
      router: {
        query: {
          id: context.params.id
        },
        locale: context.locale,
      }
    },
    revalidate: 60 * 60 // Revalidate every hour
  }
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: 'blocking'
  }
}
```

### Screenshots/Code/Logs
```
ERROR	Invoke Error 	
{
    "errorType": "AWS.SimpleQueueService.NonExistentQueue",
    "errorMessage": "The specified queue does not exist for this wsdl version.",
    "Type": "Sender",
    "Code": "AWS.SimpleQueueService.NonExistentQueue",
    "Detail": "",
    "name": "AWS.SimpleQueueService.NonExistentQueue",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "ec291cf4-224c-5bd7-972f-45da3f97bd02",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.",
        "    at /var/task/index-7e1e3de6.js:1891:68",
        "    at step (/var/task/httpRequest-31970d1c.js:89:23)",
        "    at Object.next (/var/task/httpRequest-31970d1c.js:70:53)",
        "    at fulfilled (/var/task/httpRequest-31970d1c.js:60:58)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

### Versions
I build the web with:
- @sls-next/lambda-at-edge@1.9.0-alpha.15
- next@10.2.3

Specifically:
```
#!/usr/bin/env node
const { Builder } = require("@sls-next/lambda-at-edge");

// Run the serverless builder, this could be done elsewhere in your workflow
const builder = new Builder('.', '.cdk', { args: [ 'build' ] });

builder.build()
  .then(() => {
    console.log('The build was successful');
  });
```

And later deploy with the CDK with:
- @sls-next/cdk-construct: 1.20.0-alpha.15
```
private initializeWebCloudfront(env: Environment, mainCertificate: ICertificate, mainHostedZone: IHostedZone, appSyncApi: GraphqlApi): NextJSLambdaEdge {
    const domainNames = [`${env !== Environment.prod ? env : ''}.${MAIN_DOMAIN_NAME}`];
    if (env === Environment.prod) {
      domainNames.push(`www.${MAIN_DOMAIN_NAME}`);
    }

    const nextJSCachePolicy = new CachePolicy(this, `EPollsCloudfrontDefaultCachePolicy${capitalize(env)}`, {
      cachePolicyName: `EPollsCloudfrontDefaultCachePolicy${capitalize(env)}`,
      comment: 'The default policy to be used in the cache',
      cookieBehavior: CacheCookieBehavior.all(),
      headerBehavior: CacheHeaderBehavior.allowList('Accept-Language'),
      queryStringBehavior: CacheQueryStringBehavior.all(),
      enableAcceptEncodingGzip: true,
      enableAcceptEncodingBrotli: true, // spellchecker: disable-line
    });

    const appSyncCachePolicy = new CachePolicy(this, `EPollsCloudfrontAppSyncCachePolicy${capitalize(env)}`, {
      cachePolicyName: `EPollsCloudfrontAppSyncCachePolicy${capitalize(env)}`,
      comment: 'The cache policy to be used for the AppSync endpoint',
      cookieBehavior: CacheCookieBehavior.all(),
      headerBehavior: CacheHeaderBehavior.allowList(
        'Access-Control-Allow-Origin',
        'Access-Control-Request-Headers',
        'Access-Control-Request-Method'
      ),
      queryStringBehavior: CacheQueryStringBehavior.all(),
      enableAcceptEncodingGzip: true,
      enableAcceptEncodingBrotli: true, // spellchecker: disable-line
    });

    const appSyncOriginRequestPolicy = new OriginRequestPolicy(this, `EPollsCloudfrontAppSyncOriginRequestPolicy${capitalize(env)}`, {
      originRequestPolicyName: `EPollsCloudfrontAppSyncOriginRequestPolicy${capitalize(env)}`,
      comment: 'The origin request policy to be used for the AppSync endpoint',
      cookieBehavior: OriginRequestCookieBehavior.all(),
      headerBehavior: OriginRequestHeaderBehavior.allowList(
        'x-api-key',
        'CloudFront-Viewer-Country',
        'CloudFront-Viewer-Country-Name',
        'CloudFront-Viewer-Country-Region',
        'CloudFront-Viewer-Country-Region-Name',
        'CloudFront-Viewer-City',
        'CloudFront-Viewer-Postal-Code',
        'CloudFront-Viewer-Latitude',
        'CloudFront-Viewer-Longitude',
        'CloudFront-Viewer-Time-Zone',
      ),
      queryStringBehavior: OriginRequestQueryStringBehavior.all()
    });

    const appSyncHostName = Fn.select(2, Fn.split('/', appSyncApi.graphqlUrl));
    const nextLambdaEdge = new NextJSLambdaEdge(this, `EPollsCloudfront${capitalize(env)}`, {
      serverlessBuildOutDir: '../epolls-web/.cdk',
      runtime: Runtime.NODEJS_12_X,
      memory: 1024,
      timeout: Duration.seconds(30),
      withLogging: true,
      name: {
        defaultLambda: `epolls-next-ui-${env}`,
        apiLambda: `epolls-next-api-${env}`,
        imageLambda: `epolls-next-image-${env}`
      },
      s3Props: {
        bucketName: env !== Environment.prod ? `${env}.epolls.io` : 'epolls.io',
      },
      invalidationPaths: ['/*'],
      domain: {
        domainNames,
        hostedZone: mainHostedZone,
        certificate: mainCertificate
      },
      defaultBehavior: {
        cachePolicy: nextJSCachePolicy
      },
      behaviours: { // spellchecker: disable-line
        '/graphql': {
          origin: new HttpOrigin(appSyncHostName),
          allowedMethods: AllowedMethods.ALLOW_ALL,
          viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          cachePolicy: appSyncCachePolicy,
          originRequestPolicy: appSyncOriginRequestPolicy
        }
      }
    });

    // TODO: Remove once solved https://github.com/serverless-nextjs/serverless-next.js/issues/995#issuecomment-830860521
    nextLambdaEdge.bucket.grantReadWrite(nextLambdaEdge.defaultNextLambda);

    return nextLambdaEdge;
  }
```

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
From some research it might be a region mismatch e.g in issues like https://github.com/aws/aws-sdk-java/issues/1985. See if maybe your region needs to be properly set?

Maybe @kirkness might know too, I am not personally using CDK in my daily deployments
