### ISSUE TITLE
Latest component versions die immediately

### ISSUE THREAD

**Issue by jonahallibone** [serverless-nextjs/serverless-next.js#1240]
### Describe the bug
This happens immediately when trying to deploy. Upgraded from 1.19.alpha.4. For reference this worked fine on 1.19.x using Next@11

```
jonah@jonahs-laptop privco-frontend % serverless

  error:
  TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)

  1s › Template › TypeError: Cannot read property 'name' of undefined
```

### Versions

- OS/Environment: macOS
- @sls-next/serverless-component version:
- `  component: "@sls-next/serverless-component@1.20.0-alpha.26"`
- Next.js version:
`next@11`

**Comment by dphang** [comment]
Not sure where it is failing apart from those external node dependencies `universalify` and `fs-extra`. Maybe you need to clear the cache and reinstall those packages, if that helps? Or can you add `NODE_OPTIONS=--stack-trace-limit=100` before running the command to expand the stack trace?

**Comment by jonahallibone** [comment]
@dphang I cleared the `.next`, `.serverless` and `.serverless_nextjs` folders each time i tried with the 1.20 components and they still failed almost immediately. Is there a clear cache command im missing?

**Comment by jonahallibone** [comment]
@dphang extended stack trace:
```
TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/fs-extra/lib/index.js:5:6)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/@sls-next/serverless-component/dist/component.js:27:20)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.20.0-alpha.26/node_modules/@sls-next/serverless-component/serverless.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Template.load (/snapshot/serverless/node_modules/@serverless/core/src/Component.js:106:24)
    at async fn (/snapshot/serverless/node_modules/@serverless/template/utils.js:272:25)
    at async Promise.all (index 0)
    at async executeGraph (/snapshot/serverless/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/snapshot/serverless/node_modules/@serverless/template/serverless.js:67:38)
    at async Object.runComponents (/snapshot/serverless/node_modules/@serverless/cli/src/index.js:220:17)
```

**Comment by dphang** [comment]
So it looks like a dependency problem with fs-extra/universalify. We did have an update here: https://github.com/serverless-nextjs/serverless-next.js/pull/1170 to fs-extra which perhaps could have caused the issue.

Based on your logs, it is failing on this line in `universalify/index.js`, for some reason `fn` is undefined:

```ts
'use strict'

exports.fromCallback = function (fn) {
  return Object.defineProperty(function (...args) {
    if (typeof args[args.length - 1] === 'function') fn.apply(this, args)
    else {
      return new Promise((resolve, reject) => {
        fn.apply(
          this,
          args.concat([(err, res) => err ? reject(err) : resolve(res)])
        )
      })
    }
  }, 'name', { value: fn.name })
}
```

I can't reproduce the issue myself on my Mac either. Does clearing your node modules help at all? Maybe you need to clear the entire `/Users/jonah/.serverless/components/registry/npm/@sls-next/` in case there is some dependency conflict issue.

**Comment by jonahallibone** [comment]
@dphang still no luck, tried with the latest `3.1.0-alpha.2` as well

**Comment by dphang** [comment]
Sure we can just downgrade to fs-extra 9.1.0, not a big deal as this is just used for filesystem operations at build time.

PR: https://github.com/serverless-nextjs/serverless-next.js/pull/1252

**Comment by jonahallibone** [comment]
@dphang Thanks! I tried finding any related `fs-extra` issues but failed to. Which release contained that upgrade? I can try the ones before and after it to see if it isolates the issue.

**Comment by jonahallibone** [comment]
@dphang just to confirm the deploy worked in `3.1.0-alpha.3`
