### ISSUE TITLE
Cloudfront Origins - OperationAborted: A conflicting conditional operation is currently in progress

### ISSUE THREAD

**Issue by jlaramie** [serverless-nextjs/serverless-next.js#1292]
### Describe the bug
When adding a custom origin configuration the build succeeds the first time but fails every other time unless the configuration is modified slightly before deploying again.

### Actual behavior
`OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again`

### Expected behavior
Serverless build should should complete and not attempt to change the cloudfront origins again since they are unmodified.

### Steps to reproduce
```
website:
  component: '@sls-next/serverless-component@3.1.0-alpha.13'
  inputs:
    bucketName: '${env.BUCKET_NAME}'
    bucketRegion: '${env.BUCKET_REGION}'
    domain: ['${env.SUBDOMAIN}', '${env.DOMAIN}']
    cloudfront:
      priceClass: 'PriceClass_100'
      origins:
        - url: '/page-data'
          pathPatterns:
            /files/*:
              minTTL: 0
              defaultTTL: 60
              maxTTL: 31536000
              forward:
                cookies: none
                headers: none
                queryString: false
```
I also tried 
```
website:
  component: '@sls-next/serverless-component@3.1.0-alpha.13'
  inputs:
    bucketName: '${env.BUCKET_NAME}'
    bucketRegion: '${env.BUCKET_REGION}'
    domain: ['${env.SUBDOMAIN}', '${env.DOMAIN}']
    cloudfront:
      priceClass: 'PriceClass_100'
      origins:
        - url: 'http://${env.BUCKET_NAME}.s3.${env.BUCKET_REGION}.amazonaws.com'
          pathPatterns:
            /page-data/files/*:
              minTTL: 0
              defaultTTL: 60
              maxTTL: 31536000
              forward:
                cookies: none
                headers: none
                queryString: false
```
and I tried
```
website:
  component: '@sls-next/serverless-component@3.1.0-alpha.13'
  inputs:
    bucketName: '${env.BUCKET_NAME}'
    bucketRegion: '${env.BUCKET_REGION}'
    domain: ['${env.SUBDOMAIN}', '${env.DOMAIN}']
    cloudfront:
      priceClass: 'PriceClass_100'
      origins:
        - url: '/'
          pathPatterns:
            /page-data/files/*:
              minTTL: 0
              defaultTTL: 60
              maxTTL: 31536000
              forward:
                cookies: none
                headers: none
                queryString: false
```

### Screenshots/Code/Logs
```
  DEBUG ─ Deploying bucket website in region us-east-1.
  DEBUG ─ Checking if bucket website exists.
  DEBUG ─ Setting acceleration to "true" for bucket nabor2-dev.
  DEBUG ─ Bucket website was successfully deployed to the us-east-1 region.
  DEBUG ─ Starting deployment of lambda d4fqcsh-j5crk6 to the us-east-1 region.
  DEBUG ─ Packaging lambda code from D:\Repos\website\frontend\.serverless_nextjs\api-lambda.
  DEBUG ─ Uploading d4fqcsh-j5crk6 lambda code.
  DEBUG ─ Updating d4fqcsh-j5crk6 lambda config.
  DEBUG ─ Successfully deployed lambda d4fqcsh-j5crk6 in the us-east-1 region.
  DEBUG ─ Starting deployment of lambda d4fqcsh-v07f1oa to the us-east-1 region.
  DEBUG ─ Packaging lambda code from D:\Repos\website\frontend\.serverless_nextjs\default-lambda.
  DEBUG ─ Uploading d4fqcsh-v07f1oa lambda code.
  DEBUG ─ Updating d4fqcsh-v07f1oa lambda config.
  DEBUG ─ Successfully deployed lambda d4fqcsh-v07f1oa in the us-east-1 region.
  DEBUG ─ Starting deployment of CloudFront distribution to the us-east-1 region.
  DEBUG ─ Updating CloudFront distribution of ID CLOUDFRONT_ID.

  error:
  OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
    at Request.extractError (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\services\s3.js:714:35)
    at Request.callListeners (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:106:20)    at Request.emit (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:14:12)  
    at C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:116:18)    at Request.emit (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:14:12)  
    at C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:116:18)    at callNextListener (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:96:12)      
    at IncomingMessage.onEnd (C:\Users\jorda\.serverless\components\registry\npm\@sls-next\serverless-component@3.1.0-alpha.13\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\event_listeners.js:336:13)    
    at IncomingMessage.emit (events.js:388:22)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'OperationAborted',
  region: null,
  time: 2021-06-24T14:00:13.409Z,
  requestId: 'T2W6HFSV6B5Q78H6',
  extendedRequestId: 'fkW3A4+QWiHwWLbTxfXoy8psFYFsjje6p5WiAdqrt6OpS++/ED36rfD5jc/xXG1aaLtUw15Xv9k=',
  cfId: undefined,
  statusCode: 409,
  retryable: false,
  retryDelay: 131.16319902096393
}

Done in 136.66s.
```

### Versions
`@sls-next/serverless-component@1.20.0-alpha.28`
`@sls-next/serverless-component@3.1.0-alpha.13`

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jlaramie** [comment]
I think the build is considering this as 2 different origins even though I'm just trying to add a behavior to the default origin setup. The result when it does succeed is a single origin with 1 extra behavior. I tried adding a behavior or pathPattern directly but `validatePathPatterns` requires that any of those paths actually lead to next.js pages instead of just S3 access.
