### ISSUE TITLE
The certificate that is attached to your distribution doesn't cover the alternate CNAME that your trying to add

### ISSUE THREAD

**Issue by dan-cooke** [serverless-nextjs/serverless-next.js#1492]
### Issue Summary

I am attempting to use the `domain` feature of the plugin. However I had already created a certificate for my domain before using this feature, it may be interferring with it.

### Behaviour

With `npx serverless --debug` 

This is the last step that occurs before receving an error
```
DEBUG ─ Adding www.app.link domain to CloudFront distribution with URL "https://d1m8xn0wxm34g5.cloudfront.net"

  error:
  InvalidViewerCertificate: The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME) that you're trying to add. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements
    at Request.extractError (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/danielcooke/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidViewerCertificate',
  time: 2021-08-03T11:00:56.884Z,
  requestId: '3bf84251-0506-4dfb-b3b6-e18543dd0166',
  statusCode: 400,
  retryable: false,
  retryDelay: 23.011460296687503

```

### Steps to reproduce

1. Setup a hosted zone for a domain
2. Create a certificate for the domain in ACM

Wtih the following serverless.yml
```
app: some-app
service: service
org: dancooke
app:
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
    domain: "app.link"

```
3. Run `npx serverless`

### Workaround
What i've been doing is linking my domain to cloudfront distribution that this plugin creates manually, and then specifying 

```
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
   cloudfront:
    distributionId: {id}
```

### Versions

- OS/Environment: MacOS Catalina 10.15.7
- @sls-next/serverless-component version :1.17.0
- Next.js version:10.0.7

**Comment by dphang** [comment]
Yes with the domain component, it does a lot of magic behind the scenes with Route53/Certs so it's complicated if you already have a cert. Usually that error happens when the cert does not have all the domains/subdomains added to it. If you have a complex domain setup, it might be better to just manage the cert and Route53 outside of this component (e.g terraform) and then use the certificate inputs here to point to your certificate: https://github.com/serverless-nextjs/serverless-next.js#custom-cloudfront-configuration.

BTW, 1.17 is fairly old at this point, I think the above might only be supported in newer versions.

**Comment by dan-cooke** [comment]
@dphang I see. I assumed that might be the problem. 

I'll look into setting this all up externally then. Thanks!
