### ISSUE TITLE
Using Bitbucket Pipelines to deploy to AWS

### ISSUE THREAD

**Issue by shoremark** [serverless-nextjs/serverless-next.js#166]
# What I am trying to do
I would like to deploy serverless-next.js to AWS using bitbucket pipelines. I am using the component version of Serverless Next.js. I know there is a current bug #147 with using CI for deploying that requires you to store the `.serverless` the folder in the repo to get around this for multiple environments. I have created multiple versions of the folder for each environment such as `.serverless-testing`. When the CI runs I rename the folder to `.serverless` to use a specific deployment with an account-specific Key and Secret. This process works locally but in the CI I am getting an error that is hard to debug due to it gives very few specifics about the issue. Is there any way to get more information on what is causing the error below or any ideas what would cause this type of issue?

## Code used to deploy
```
- npm update -g serverless
- yarn install
- mv .serverless-testing .serverless
- export AWS_ACCESS_KEY_ID=$AWS_KEY_DEV
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_DEV
- export AWS_REGION=us-east-1
- npx serverless --debug
```

## Error message in Pipelines
```
aNA
  36s › XXXXXXXXX › Deploying .
aNA  DEBUG ─ Deploying bucket XXXXXXXXX in region us-east-1.
  DEBUG ─ Checking if bucket XXXXXXXXX exists.
  36s › XXXXXXXXX › Deploying ..
aNA
  36s › XXXXXXXXX › Deploying ..
aNA
  error:
  { BadRequest: null
    at Request.extractError (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/services/s3.js:565:35)
    at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.2.3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: null,
  code: 'BadRequest',
  region: null,
  time: 2019-09-26T18:27:53.503Z,
  requestId: '4C177204725A0344',
  extendedRequestId: 'XXXXXXXXX',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 91.31035499367705 }
  36s › XXXXXXXXX › BadRequest: null
```

## Questions
1.  What would cause this error?
2. Is there any way to get more information on this error other than `--debug`?
3. Is there a better practice in setting up multiple environments for CI deployments other than renaming the `.serverless` folder?

**Comment by danielcondemarin** [comment]
@shoremark I appreciate is has been a while, sorry for the late reply. Are you still running into this issue?

**Comment by polc** [comment]
FYI it can happen after deleting & trying recreating a S3 bucket. It take from 10 minutes to a few hours for the S3 bucket name to be available again.

**Comment by Jhenri-silva** [comment]
I facing the same issue 

I don't have any ideia of what it is
```
error:
  BadRequest: null
    at Request.extractError (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\services\s3.js:680:35)
    at Request.callListeners (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\snake\.serverless\components\registry\npm\@sls-next\serverless-component@1.16.0\node_modules\@sls-next\serverless-component\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'BadRequest',
  region: null,
  time: 2020-10-13T14:24:56.619Z,
  requestId: '6CBC8AF139C3E4F4',
  extendedRequestId: 'Cgp+tcBufSzrNFiC/5fxQLeADjzwfnawlisRiXVHpQfYPcHREB/ARguSBmncsB/idGewpJGwPBM=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 93.48166756334864
}

  50s » riskassesment » BadRequest: null
```

**Comment by dphang** [comment]
@Jhenri-silva it is either S3 bucket creation or upload issue, ensure you have access to create that bucket and/or name is not already taken, and also if it was recently deleted it takes some time to get the name back

**Comment by Jhenri-silva** [comment]
> @Jhenri-silva it is either S3 bucket creation or upload issue, ensure you have access to create and write to that bucket and/or name is not already taken, and also if it was recently deleted it takes some time to get the name back

I just reset my access token id and secret on my .aws file, and works fine.

**Comment by dphang** [comment]
Closing old issue - it seems this should be resolved. Please reopen new one if there are further issues.
