### ISSUE TITLE
Deploy fails after opting in to new Lambda states

### ISSUE THREAD

**Issue by domeq** [serverless-nextjs/serverless-next.js#1976]
### Issue Summary
Amazon seems to be expanding Lambda function states - read more [here](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/).
This is planned to kick in 1 Nov 2021.

tl;dr is: 
This change can impact workflow patterns which update a function right after creating or modifying it, which can cause function update fail.

After experimentally opting in for this (as instructed in the blog post above), my application no longer deploys.

### Actual behavior
Running `npx serverless` ends up with the following error:
```
 error:
  ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:801001371903:function:pent2-web-feature-image-lambda
    at Object.extractError (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/travis/build/niche-and-services/pent2-web/node_modules/aws-sdk/lib/event_listeners.js:336:13)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ResourceConflictException',
  time: 2021-10-28T14:10:21.087Z,
  requestId: '16b80c4e-6e61-4337-aad8-013eaa51c70f',
  statusCode: 409,
  retryable: false,
  retryDelay: 6.8138474319063835
}
```

### Expected behavior
App should deploy normally.

### Steps to reproduce

1. Set `inputs.description`  field in your config to `aws:states:opt-in`
2. Run `npx serverless`
3. It should fail after ~a minute.

### Versions

- OS/Environment: Mac OS / Linux (Travis)
- @sls-next/serverless-component version: `3.5.2`
- Next.js version: `11.1.0`

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Hm, weird, I guess the wait needs to happen after the code is uploaded. Let me move the wait up earlier

**Comment by dphang** [comment]
I think it _should_ be fixed now, please confirm and I can close this

**Comment by dphang** [comment]
Woops, 3rd time's the charm, hopefully this fixes now: https://github.com/serverless-nextjs/serverless-next.js/pull/1992

**Comment by domeq** [comment]
Yes, I can confirm `3.5.3-alpha.4` is working just fine for me too 👍🏻 

Thanks a lot for your help and a quick fix 👏🏻
