### ISSUE TITLE
NoSuchDistribution: The specified distribution does not exist.

### ISSUE THREAD

**Issue by romansemko** [serverless-nextjs/serverless-next.js#2100]
I have a live deployed project with serverless 3.1.0. Re-deploying failed this morning (because of lambda issue) so I upgraded to serverless-components 3.5.3 as advised. However, the deployment fails with the following error:

```
❯ serverless

  error:
  NoSuchDistribution: The specified distribution does not exist.
    at Request.extractError (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/roman/.serverless/components/registry/npm/@sls-next/serverless-component@3.5.3/node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'NoSuchDistribution',
  time: 2021-11-22T08:09:52.531Z,
  requestId: 'b74eb7aa-bade-4d53-b769-1a7cf1b00c58',
  statusCode: 404,
  retryable: false,
  retryDelay: 104.03510550497037
}
```

v.3.6.0 has the same issue. My serverless.yml config looks like follows:

```
app:
  component: "@sls-next/serverless-component@v3.5.3"
  inputs:
    domain: "mydomain.com"
    build:
      env:
        SOME_ENV: "test"
```

Not sure what the issue is here. Do I need to re-create the whole distribution after upgrading the serverless-components? I would like to prevent any downtimes here..

**Comment by romansemko** [comment]
Running with `--debug` there is some additional, interesting info:

```
DEBUG ─ Deploying bucket zcjelf5-c9m1ad8 in region us-east-1.
  DEBUG ─ Checking if bucket zcjelf5-c9m1ad8 exists.
  DEBUG ─ Setting acceleration to "true" for bucket zcjelf5-c9m1ad8.
  DEBUG ─ Bucket zcjelf5-c9m1ad8 was successfully deployed to the us-east-1 region.
  DEBUG ─ Starting deployment of lambda zcjelf5-api1qxl to the us-east-1 region.
  DEBUG ─ Syncing role zcjelf5-q0jjrkk in region us-east-1.
  DEBUG ─ Saved state for role zcjelf5-q0jjrkk.
  DEBUG ─ Role zcjelf5-q0jjrkk was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::995055353456:role/zcjelf5-q0jjrkk.
  DEBUG ─ Packaging lambda code from /Users/roman/Workspace/alchemy.dapp/.serverless_nextjs/api-lambda.
  DEBUG ─ Uploading zcjelf5-api1qxl lambda code.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-api1qxl to be ready.
  DEBUG ─ Updating zcjelf5-api1qxl lambda config.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-api1qxl to be ready.
  DEBUG ─ Successfully deployed lambda zcjelf5-api1qxl in the us-east-1 region.
  DEBUG ─ Starting deployment of lambda zcjelf5-kc0spr to the us-east-1 region.
  DEBUG ─ Syncing role zcjelf5-i9j6rnl in region us-east-1.
  DEBUG ─ Saved state for role zcjelf5-i9j6rnl.
  DEBUG ─ Role zcjelf5-i9j6rnl was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::995055353456:role/zcjelf5-i9j6rnl.
  DEBUG ─ Packaging lambda code from /Users/roman/Workspace/alchemy.dapp/.serverless_nextjs/image-lambda.
  DEBUG ─ Uploading zcjelf5-kc0spr lambda code.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-kc0spr to be ready.
  DEBUG ─ Updating zcjelf5-kc0spr lambda config.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-kc0spr to be ready.
  DEBUG ─ Successfully deployed lambda zcjelf5-kc0spr in the us-east-1 region.
  DEBUG ─ Starting deployment of lambda zcjelf5-s8cp9eh to the us-east-1 region.
  DEBUG ─ Syncing role zcjelf5-37vsq67 in region us-east-1.
  DEBUG ─ Saved state for role zcjelf5-37vsq67.
  DEBUG ─ Role zcjelf5-37vsq67 was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::995055353456:role/zcjelf5-37vsq67.
  DEBUG ─ Packaging lambda code from /Users/roman/Workspace/alchemy.dapp/.serverless_nextjs/default-lambda.
  DEBUG ─ Uploading zcjelf5-s8cp9eh lambda code.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-s8cp9eh to be ready.
  DEBUG ─ Updating zcjelf5-s8cp9eh lambda config.
  DEBUG ─ Waiting up to 600 seconds for Lambda zcjelf5-s8cp9eh to be ready.
  DEBUG ─ Successfully deployed lambda zcjelf5-s8cp9eh in the us-east-1 region.
  DEBUG ─ Starting deployment of CloudFront distribution to the us-east-1 region.
  DEBUG ─ Updating CloudFront distribution of ID E3J8KKXHSRGRVP.

  error:
  NoSuchDistribution: The specified distribution does not exist.
```

When I check the cloudfront distros I, indeed, do not see any CloudFront distribution with ID E3J8KKXHSRGRVP on AWS. Not sure where it is being taken from. There is only one AWS account. So not confusion there.

**Comment by enzoames** [comment]
For anyone who is looking at this. I solved this by deleting the `.serverless/` and `.serverless_nextjs` directories and deploying one more time. 
Looking back, I got into this issue by deleting the distribution manually from cloudfront on the aws console, which maybe I shouldnt have done but next time i know what to do.

**Comment by atnp-it** [comment]
@enzoames Thanks you!
