### ISSUE TITLE
Error in resolving using arguments - invalid reference ${opt:stage}

### ISSUE THREAD

**Issue by hemikak** [serverless-nextjs/serverless-next.js#2219]
I am using the 3.6.0 version of the component and I am unable to use `${opt:stage}` in my serverless.yaml definition. 
This is the command I am executing:
```
yarn serverless --stage integration --debug
```

This is the error I am getting:
```
  error:
  Error: invalid reference ${opt:stage}
    at Object.<anonymous> (/Users/hemikak/abc/node_modules/@serverless/template/utils.js:128:19)
    at walker (/Users/hemikak/abc/node_modules/traverse/index.js:190:22)
    at /Users/hemikak/abc/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/Users/hemikak/abc/node_modules/traverse/index.js:298:31)
    at walker (/Users/hemikak/aabc/node_modules/traverse/index.js:203:13)
    at /Users/hemikak/abc/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/Users/hemikak/abc/node_modules/traverse/index.js:298:31)
    at walker (/Users/hemikak/abc/node_modules/traverse/index.js:203:13)
```

**Comment by pomSense** [comment]
As per this [issue](https://github.com/serverless-nextjs/serverless-next.js/issues/199), you can use dot notation:
```
${opt.stage}
```
