### ISSUE TITLE
webpack/runtime/compat The "path" argument must be of type string. Received undefined with new Worker(new URL(...)) and comlink

### ISSUE THREAD

**Issue by talaikis** [serverless-nextjs/serverless-next.js#2220]
### Issue Summary

webpack/runtime/compat The "path" argument must be of type string. Received undefined with new Worker(new URL(...)) and comlink

### Actual behavior

```
webpack/runtime/compat The "path" argument must be of type string
```

### Expected behavior

Probably should work, because nextjs build worksfine.

### Steps to reproduce

Repo: https://github.com/talaikis/next-worker-comlink-repro

on deployment gives Error:

```bash
warn  - No ESLint configuration detected. Run next lint to begin setup
Failed to compile.

webpack/runtime/compat
The "path" argument must be of type string. Received undefined


> Build failed because of webpack errors
info  - Checking validity of types...
info  - Creating an optimized production build...
    at makeError (C:\Users\DXenu\.serverless\components\registry\npm\@sls-next\serverless-component@3.6.0\node_modules\@sls-next\serverless-component\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\DXenu\.serverless\components\registry\npm\@sls-next\serverless-component@3.6.0\node_modules\@sls-next\serverless-component\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Builder.build (C:\Users\DXenu\.serverless\components\registry\npm\@sls-next\serverless-component@3.6.0\node_modules\@sls-next\serverless-component\node_modules\@sls-next\lambda-at-edge\dist\build.js:377:13)
    at async NextjsComponent.build (C:\Users\DXenu\.serverless\components\registry\npm\@sls-next\serverless-component@3.6.0\node_modules\@sls-next\serverless-component\dist\component.js:165:13)
    at async NextjsComponent.default (C:\Users\DXenu\.serverless\components\registry\npm\@sls-next\serverless-component@3.6.0\node_modules\@sls-next\serverless-component\dist\component.js:22:13)
    at async fn (\with-next-worker-repro\node_modules\@serverless\template\utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (\with-next-worker-repro\node_modules\@serverless\template\utils.js:294:3)
    at async Template.default (\with-next-worker-repro\node_modules\@serverless\template\serverless.js:67:38) {
  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
  command: 'node_modules/.bin/next build',
  escapedCommand: '"node_modules/.bin/next" build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'info  - Checking validity of types...\n' +
    'info  - Creating an optimized production build...',
  stderr: 'warn  - The `target` config is deprecated and will be removed in a future version.\n' +
    'See more info here https://nextjs.org/docs/messages/deprecated-target-config\n' +
    'warn  - No ESLint configuration detected. Run next lint to begin setup\n' +
    'Failed to compile.\n' +
    '\n' +
    'webpack/runtime/compat\n' +
    'The "path" argument must be of type string. Received undefined\n' +
    '\n' +
    '\n' +
    '> Build failed because of webpack errors',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Versions

- OS/Environment: Windows 11
- @sls-next/serverless-component version: 3.6.0
- Next.js version: 12.0.7

### Checklist

- [ x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by manmal** [comment]
I got this error when importing (or requiring) a relative path in a file that the web worker imports.

The following workaround worked for me: 

```typescript
const properties = require(path.join(process.cwd(), `data/file.json`));
```

instead of

```typescript
const properties = require(`../data/file.json`));
```

**Comment by talaikis** [comment]
Well, without any relative imports, it does not work with imported packages.
