### ISSUE TITLE
Variable interpolation on inputs

### ISSUE THREAD

**Issue by walter-tt** [serverless-nextjs/serverless-next.js#2255]
### Issue Summary
Whe are trying to use multiple stage deployment on CI with variable interpolation, but it doesn't seem to be working

### Actual behavior
When trying to pass the domain input from file or self variables it fails to interpolates it giving an InvalidDomainName error from AWS SDK.

our config file looks:
```

name: exampleFE

nextApp:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    domain: [ "fe" , " ${self:custom.example.${opt:stage, 'dev'}}" ] 
    memory: 1024

myTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: Customers

custom:
  optera:
    dev: dev.example.com
    prod: example.com
```
Command output:
```
sls --debug --stage dev   
DEBUG ─ Formatting domains and identifying cloud services being used.
  DEBUG ─ Getting the Hosted Zone ID for the domain ${self:custom.example.${opt:stage, 'dev'}}.

  error:
  InvalidDomainName: FATAL problem: UnsupportedCharacter (Value contains unsupported characters) encountered with ' '
    at Request.extractError (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/.serverless/components/registry/npm/@sls-next/serverless-component@3.6.0/node_modules/@sls-next/domain/node_modules/aws-sdk/lib/event_listeners.js:335:13)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'InvalidDomainName',
  time: 2022-01-10T18:49:56.632Z,
  requestId: 'xxxxxxxxxxxxxxxxxxxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 84.18566228944444
```

### Expected behavior  
Directly putting the input works, so far we workaround this with per stage serverless.yml files, and making the CI manages this, but shouldn't it be working with variables?

### Versions

- OS/Environment: Linux Ubuntu 20.04
- @sls-next/serverless-component version: 3.6.0
- Next.js version: 11.1.3

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by nathan-at-jisc** [comment]
Also having the same issue as above, here's my `yml` file

```
stage: ${env.STAGE}

octopus-next-app:
  component: "@sls-next/serverless-component@3.6.0"
  inputs:
    domain: "${custom.sub.${stage}, custom.sub.other}"

custom:
  sub:
    prod:
      - "octopus.ac"
    other:
      - "${stage}"
      - "octopus.ac"
```

**Comment by walter-tt** [comment]
Hey @nathan-at-jisc alraedy figured this out. nextjs component just doesnt support stages. There are a few workarounds this, but as I use a CI for this I prefered the _per stage file_ approach. One per stage you need,  like `serverless.stage.yml` and then on you CI (or your deployment script) you can copy the stage of your choice to `serverless.yml` and run `sls`
