### ISSUE TITLE
`regenerationLambda` erroring in `v3.7.0-alpha.7`

### ISSUE THREAD

**Issue by b3nThomas** [serverless-nextjs/serverless-next.js#2318]
### Issue Summary
Messages are making it via SQS to the regen lambda, however invoke errors are being thrown, preventing the page from being regenerated. (Details below)

### Actual behavior
My page is not being regenerated. I can tell this as the `last-modified` header for my html page remains unchanged. Instead, I'm served with the page that was originally stored in S3 when I performed my serverless deployment.

### Expected behavior
My page should be regenerated every 30s. I should be able to see the `last-modified` header update once ISR has been successfully performed.

### Steps to reproduce
- Deploy your app with `revalidate` configured on a static page. (I set mine to 30s just to test that it was working)
- Once deployed, check the time on the `last-modified` header for the page. It should match when the file was uploaded to S3.
- Note that no matter how long you wait and keep refreshing, the time on the header never changes.
- Look in SQS > monitoring and note that messages are trickling down the queue to the regen lambda.
- Look in CloudWatch and look at the logs for your regen Lambda. Note the invoke errors that are being thrown repeatedly.

#### `Root` package.json dependencies
```json
    "dependencies": {
        "@vanilla-extract/css": "^1.6.8",
        "config": "^3.3.7",
        "i18next": "^21.6.6",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-i18next": "^11.15.1",
        "superstruct": "^0.15.3"
    },
```

#### `Site` package.json dependencies
```json
    "dependencies": {
        "graphql-tag": "^2.12.6",
        "next": "^12.0.7",
        "next-i18next": "^10.0.1"
    },
```
#### serverless.yml config
```yml
# ./packages/site/serverless.yml
dotComSite:
    component: '@sls-next/serverless-component@v3.7.0-alpha.7'
    inputs:
        build:
            cmd: '../../node_modules/.bin/next'
            env:
                NODE_ENV: 'production'
            outputFileTracing: true
```

#### next.config.js
```typescript
/** @type {import('next').NextConfig} */
import transpileModules from 'next-transpile-modules';
import { createVanillaExtractPlugin } from '@vanilla-extract/next-plugin';
import withPlugins from 'next-compose-plugins';
import i18nConfig from './next-i18next.config.js';

const plugins = [transpileModules(['components']), createVanillaExtractPlugin()];

export default withPlugins(plugins, {
    i18n: i18nConfig.i18n,
    reactStrictMode: true,
    // Avoid exposing easy to access implementation details
    poweredByHeader: false,
    webpack(config) {
        config.module.rules.push({
            test: /\.graphql/,
            exclude: /node_modules/,
            loader: 'graphql-tag/loader',
        });

        return config;
    },
});
```
#### CloudWatch errors:
```
2022-01-27T12:13:40.868Z	8c4a505e-4df3-5e64-9c76-0a32c3513ba4	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "page.renderReqToHTML is not a function",
    "stack": [
        "TypeError: page.renderReqToHTML is not a function",
        "    at renderPageToHtml (/var/task/index.js:16787:57)",
        "    at /var/task/index.js:97808:44",
        "    at Array.map (<anonymous>)",
        "    at Runtime.handler (/var/task/index.js:97802:37)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

2022-01-27T12:13:40.874Z	8c4a505e-4df3-5e64-9c76-0a32c3513ba4	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Cannot find module 'react/jsx-runtime'\nRequire stack:\n- /var/task/pages/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Cannot find module 'react/jsx-runtime'\nRequire stack:\n- /var/task/pages/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
        "code": "MODULE_NOT_FOUND",
        "requireStack": [
            "/var/task/pages/index.js",
            "/var/task/index.js",
            "/var/runtime/UserFunction.js",
            "/var/runtime/index.js"
        ],
        "stack": [
            "Error: Cannot find module 'react/jsx-runtime'",
            "Require stack:",
            "- /var/task/pages/index.js",
            "- /var/task/index.js",
            "- /var/runtime/UserFunction.js",
            "- /var/runtime/index.js",
            "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
            "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
            "    at Module.require (internal/modules/cjs/loader.js:974:19)",
            "    at require (internal/modules/cjs/helpers.js:93:18)",
            "    at Object.997 (/var/task/pages/index.js:1439:18)",
            "    at __webpack_require__ (/var/task/webpack-runtime.js:25:42)",
            "    at /var/task/pages/index.js:407:75",
            "    at Function.__webpack_require__.a (/var/task/webpack-runtime.js:98:13)",
            "    at Object.8544 (/var/task/pages/index.js:399:21)",
            "    at __webpack_require__ (/var/task/webpack-runtime.js:25:42)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Cannot find module 'react/jsx-runtime'",
        "Require stack:",
        "- /var/task/pages/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}

2022-01-27T12:13:40.875+00:00 [ERROR] [1643285620875] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.

2022-01-27T12:13:40.890+00:00 END RequestId: 8c4a505e-4df3-5e64-9c76-0a32c3513ba4

2022-01-27T12:13:40.890+00:00 REPORT RequestId: 8c4a505e-4df3-5e64-9c76-0a32c3513ba4	Duration: 245.86 ms	Billed Duration: 246 ms	Memory Size: 512 MB	Max Memory Used: 33 MB	

2022-01-27T12:13:40.890+00:00 Unknown application error occurred
```

### Versions
- OS/Environment: macOS Mojave 10.14.6
- @sls-next/serverless-component version: `v3.7.0-alpha.7`
- Next.js version: `^12.0.7`

### Additional context
Just want to say thanks for all the hard work that goes into this awesome package 🙏 

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by b3nThomas** [comment]
Closing this issue for now as I can see this experimental feature has been reverted:
https://github.com/serverless-nextjs/serverless-next.js/pull/2324
