### ISSUE TITLE
`req.query` missing for api routes in `v3.7.0-alpha.7`

### ISSUE THREAD

**Issue by b3nThomas** [serverless-nextjs/serverless-next.js#2319]
### Issue Summary
`req.query` is not being added to requests for api routes.

### Actual behavior
When hitting a simple api route with query params, I receive the bog standard `503 ERROR - The request could not be satisfied.` CloudFront error.

### Expected behavior
I should be able to successfully hit a simple api route which uses query params and receive the relevant response. 

### Steps to reproduce
- Deploy your app with an api route that uses `req.query`.
- Hit that endpoint in your deployed app.
- Note that you just get the standard `503 ERROR - The request could not be satisfied.` CloudFront error.
- Check CloudWatch logs.
- Note that the error `Cannot read property '<abc>' of undefined` is being thrown, `undefined` being `req.query`.

#### serverless.yml config
```yml
# ./packages/site/serverless.yml
dotComSite:
    component: '@sls-next/serverless-component@v3.7.0-alpha.7'
    inputs:
        build:
            cmd: '../../node_modules/.bin/next'
            env:
                NODE_ENV: 'production'
            outputFileTracing: true
```

#### next.config.js
```typescript
/** @type {import('next').NextConfig} */
import transpileModules from 'next-transpile-modules';
import { createVanillaExtractPlugin } from '@vanilla-extract/next-plugin';
import withPlugins from 'next-compose-plugins';
import i18nConfig from './next-i18next.config.js';

const plugins = [transpileModules(['components']), createVanillaExtractPlugin()];

export default withPlugins(plugins, {
    i18n: i18nConfig.i18n,
    reactStrictMode: true,
    // Avoid exposing easy to access implementation details
    poweredByHeader: false,
    webpack(config) {
        config.module.rules.push({
            test: /\.graphql/,
            exclude: /node_modules/,
            loader: 'graphql-tag/loader',
        });

        return config;
    },
});
```
#### Simple API route
```typescript
// packages/site/src/pages/api/hello.ts
import type { NextApiRequest, NextApiResponse } from 'next';

export default (req: NextApiRequest, res: NextApiResponse) => {
    console.log({ req }); // eslint-disable-line <--- I put this is to try and see what's going on with `req`.

    const name = req.query.name || 'No Name';

    res.status(200).json({ message: `Hello ${name}!` });
};
```

#### CloudWatch errors:
```
2022-01-27T14:55:41.352Z	68049390-7fbd-47f4-971c-9d5ea5710984	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'name' of undefined",
    "stack": [
        "TypeError: Cannot read property 'name' of undefined",
        "    at Module.__WEBPACK_DEFAULT_EXPORT__ (/var/task/pages/api/hello.js:20:26)",
        "    at handleApi (/var/task/index.js:1480:30)",
        "    at Runtime.handler (/var/task/index.js:1537:28)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
// This is the full `req` object that I console logged out:
2022-01-27T14:55:41.350Z	68049390-7fbd-47f4-971c-9d5ea5710984	INFO	{
  req: Readable {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: true,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: true,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    setTimeout: [Function: setTimeout],
    _read: [Function: _read],
    destroy: [Function: destroy],
    _addHeaderLines: [Function: _addHeaderLines],
    _addHeaderLine: [Function: _addHeaderLine],
    _dump: [Function: _dump],
    url: '/api/hello?name=Ben',
    method: 'GET',
    rawHeaders: [
      'Host',
      'd2qzeqgc7la3qy.cloudfront.net',
      'X-Forwarded-For',
      '165.225.199.76',
      'User-Agent',
      'Amazon CloudFront',
      'Via',
      '2.0 b9061e936b29505d1b542db7af99b46c.cloudfront.net (CloudFront)',
      'Accept-Encoding',
      'gzip',
      'Pragma',
      'no-cache',
      'sec-ch-ua',
      '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
      'sec-ch-ua-mobile',
      '?0',
      'sec-ch-ua-platform',
      '"macOS"',
      'upgrade-insecure-requests',
      '1',
      'sec-fetch-site',
      'none',
      'sec-fetch-mode',
      'navigate',
      'sec-fetch-user',
      '?1',
      'sec-fetch-dest',
      'document',
      'Cache-Control',
      'no-cache'
    ],
    headers: {
      host: 'd2qzeqgc7la3qy.cloudfront.net',
      'x-forwarded-for': '165.225.199.76',
      'user-agent': 'Amazon CloudFront',
      via: '2.0 b9061e936b29505d1b542db7af99b46c.cloudfront.net (CloudFront)',
      'accept-encoding': 'gzip',
      pragma: 'no-cache',
      'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'upgrade-insecure-requests': '1',
      'sec-fetch-site': 'none',
      'sec-fetch-mode': 'navigate',
      'sec-fetch-user': '?1',
      'sec-fetch-dest': 'document',
      'cache-control': 'no-cache'
    },
    connection: {},
    getHeader: [Function (anonymous)],
    getHeaders: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}
```

### Versions
- OS/Environment: macOS Mojave 10.14.6
- @sls-next/serverless-component version: `v3.7.0-alpha.7`
- Next.js version: `^12.0.7`

### Additional context
Just want to say thanks _again_ for all the hard work that goes into this awesome package 🙏 

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by b3nThomas** [comment]
Closing this issue for now as I can see this experimental feature has been reverted:
https://github.com/serverless-nextjs/serverless-next.js/pull/2324
