### ISSUE TITLE
Serverless Components CLI v1 is no longer bundled with Serverless Framework CLI

### ISSUE THREAD

**Issue by CervarlCG** [serverless-nextjs/serverless-next.js#2320]
### Issue Summary

When i try to deploy an app then i receive the next message: 

> Serverless Components CLI v1 is no longer bundled with Serverless Framework CLI

and the app is not deployed

### Actual behavior

The process end with that message

### Expected behavior

Tha app is deployed

### Steps to reproduce

Try to deploy a app with @sls-next/serverless-component@3.7.0-alpha.7

### Screenshots/Code/Configuration/Logs

![Screen Shot 2022-01-27 at 15 12 12](https://user-images.githubusercontent.com/53922412/151444605-b3a2241e-ff85-4873-b72c-97e13d7895c2.png)
![Screen Shot 2022-01-27 at 15 13 46](https://user-images.githubusercontent.com/53922412/151444627-daa92bd4-d2d5-4811-a4d9-05ecf479e668.png)

### Versions

- OS/Environment: Ubuntu
- @sls-next/serverless-component version: 3.7.0-alpha.7
- Next.js version: 12

### Checklist

- [ ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Hm, seems some others faced this too, I think you could pin to an older version of serverless@2.72.2 when deploying which will have the old beta serverless components in it and it should work?

**Comment by CervarlCG** [comment]
@dphang i tried with a older version but i have the same problem

Serverless released a new version today and i think that the new version break the workflow because it separate the Component CLI from the  Serverless Framework CLI

**Comment by ferdingler** [comment]
Try this to deploy: 
```
npx serverless@2.72.2
```

**Comment by CervarlCG** [comment]
@ferdingler Thanks, that work for now.

**Comment by EhtashamAli** [comment]
Glad that I looked at recent issues created on the Repo.
Thanks @ferdingler

**Comment by alirezavlz** [comment]
Same issue here!

**Comment by uclaeamsavino** [comment]
Is there a long term solution for this? Has anyone tried the recommendation in the serverless message? I wasn't sure what to put for <command> and <options>

**Comment by luizwhite** [comment]
Same here:

`Serverless Components CLI v1 is no longer bundled with Serverless Framework CLI`

It asks to do this:

```
To run it, ensure it's installed:
npm install -g @serverless/cli

Then run:
components-v1 <command> <options>
```

When I try to use `npx serverless`

**Comment by CervarlCG** [comment]
How @ferdingler says, we have to specify the serverless version in the console, specifically a version before of 3.0.

We have to await for someone of the contributors release a new version or somebody is free to submit a pull request with a modification in the serverless version while the integrations with serverless@3 is ready

**Comment by janklan** [comment]
I got the same problem. I ran `components-v1` and it started deploying, until it failed with a rather verbose output:

```

  error:
  Error: Command failed with exit code 1: node_modules/.bin/next build
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
Failed to compile.

./node_modules/next/dist/compiled/@vercel/nft/LICENSE
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Copyright 2019 Vercel, Inc.
| 
| Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

Import trace for requested module:
./node_modules/next/dist/compiled/@vercel/nft/ sync ^\.\/.*$
./node_modules/next/dist/compiled/@vercel/nft/index.js
./node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
./node_modules/next/dist/build/webpack-config.js
./node_modules/next/dist/server/dev/hot-reloader.js
./node_modules/next/dist/server/dev/next-dev-server.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

./node_modules/next/dist/compiled/webpack/bundle5.js:141344:0
Module not found: Can't resolve 'next/dist/build/webpack/plugins/terser-webpack-plugin'

Import trace for requested module:
./node_modules/next/dist/compiled/webpack/webpack.js
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:9:0
Module not found: Can't resolve 'webpack5/lib/javascript/BasicEvaluatedExpression'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:11:0
Module not found: Can't resolve 'webpack5/lib/ModuleFilenameHelpers'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:13:0
Module not found: Can't resolve 'webpack5/lib/node/NodeTargetPlugin'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found


> Build failed because of webpack errors
info  - Loaded env from /Users/janklan/dev/website/.env.local
info  - Loaded env from /Users/janklan/dev/website/.env
info  - Checking validity of types...
info  - Creating an optimized production build...
    at makeError (/Users/janklan/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/janklan/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Builder.build (/Users/janklan/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/lambda-at-edge/dist/build.js:421:17)
    at async NextjsComponent.build (/Users/janklan/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/serverless-component/dist/component.js:170:13)
    at async NextjsComponent.default (/Users/janklan/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/serverless-component/dist/component.js:22:13)
    at async fn (/Users/janklan/.nvm/versions/node/v16.13.1/lib/node_modules/@serverless/cli/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/Users/janklan/.nvm/versions/node/v16.13.1/lib/node_modules/@serverless/cli/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/Users/janklan/.nvm/versions/node/v16.13.1/lib/node_modules/@serverless/cli/node_modules/@serverless/template/serverless.js:67:38) {
  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
  command: 'node_modules/.bin/next build',
  escapedCommand: '"node_modules/.bin/next" build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'info  - Loaded env from /Users/janklan/dev/website/.env.local\n' +
    'info  - Loaded env from /Users/janklan/dev/website/.env\n' +
    'info  - Checking validity of types...\n' +
    'info  - Creating an optimized production build...',
  stderr: 'warn  - The `target` config is deprecated and will be removed in a future version.\n' +
    'See more info here https://nextjs.org/docs/messages/deprecated-target-config\n' +
    'Failed to compile.\n' +
    '\n' +
    './node_modules/next/dist/compiled/@vercel/nft/LICENSE\n' +
    'Module parse failed: Unexpected token (1:10)\n' +
    'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
    '> Copyright 2019 Vercel, Inc.\n' +
    '| \n' +
    '| Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n' +
    '\n' +
    'Import trace for requested module:\n' +
    './node_modules/next/dist/compiled/@vercel/nft/ sync ^\\.\\/.*$\n' +
    './node_modules/next/dist/compiled/@vercel/nft/index.js\n' +
    './node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js\n' +
    './node_modules/next/dist/build/webpack-config.js\n' +
    './node_modules/next/dist/server/dev/hot-reloader.js\n' +
    './node_modules/next/dist/server/dev/next-dev-server.js\n' +
    './node_modules/next/dist/server/next.js\n' +
    './node_modules/@sentry/nextjs/dist/utils/instrumentServer.js\n' +
    './node_modules/@sentry/nextjs/dist/index.server.js\n' +
    './sentry.server.config.js\n' +
    '\n' +
    './node_modules/next/dist/compiled/webpack/bundle5.js:141344:0\n' +
    "Module not found: Can't resolve 'next/dist/build/webpack/plugins/terser-webpack-plugin'\n" +
    '\n' +
    'Import trace for requested module:\n' +
    './node_modules/next/dist/compiled/webpack/webpack.js\n' +
    './node_modules/next/dist/server/config-utils.js\n' +
    './node_modules/next/dist/server/config.js\n' +
    './node_modules/next/dist/server/next.js\n' +
    './node_modules/@sentry/nextjs/dist/utils/instrumentServer.js\n' +
    './node_modules/@sentry/nextjs/dist/index.server.js\n' +
    './sentry.server.config.js\n' +
    '\n' +
    'https://nextjs.org/docs/messages/module-not-found\n' +
    '\n' +
    './node_modules/next/dist/compiled/webpack/webpack.js:9:0\n' +
    "Module not found: Can't resolve 'webpack5/lib/javascript/BasicEvaluatedExpression'\n" +
    '\n' +
    'Import trace for requested module:\n' +
    './node_modules/next/dist/server/config-utils.js\n' +
    './node_modules/next/dist/server/config.js\n' +
    './node_modules/next/dist/server/next.js\n' +
    './node_modules/@sentry/nextjs/dist/utils/instrumentServer.js\n' +
    './node_modules/@sentry/nextjs/dist/index.server.js\n' +
    './sentry.server.config.js\n' +
    '\n' +
    'https://nextjs.org/docs/messages/module-not-found\n' +
    '\n' +
    './node_modules/next/dist/compiled/webpack/webpack.js:11:0\n' +
    "Module not found: Can't resolve 'webpack5/lib/ModuleFilenameHelpers'\n" +
    '\n' +
    'Import trace for requested module:\n' +
    './node_modules/next/dist/server/config-utils.js\n' +
    './node_modules/next/dist/server/config.js\n' +
    './node_modules/next/dist/server/next.js\n' +
    './node_modules/@sentry/nextjs/dist/utils/instrumentServer.js\n' +
    './node_modules/@sentry/nextjs/dist/index.server.js\n' +
    './sentry.server.config.js\n' +
    '\n' +
    'https://nextjs.org/docs/messages/module-not-found\n' +
    '\n' +
    './node_modules/next/dist/compiled/webpack/webpack.js:13:0\n' +
    "Module not found: Can't resolve 'webpack5/lib/node/NodeTargetPlugin'\n" +
    '\n' +
    'Import trace for requested module:\n' +
    './node_modules/next/dist/server/config-utils.js\n' +
    './node_modules/next/dist/server/config.js\n' +
    './node_modules/next/dist/server/next.js\n' +
    './node_modules/@sentry/nextjs/dist/utils/instrumentServer.js\n' +
    './node_modules/@sentry/nextjs/dist/index.server.js\n' +
    './sentry.server.config.js\n' +
    '\n' +
    'https://nextjs.org/docs/messages/module-not-found\n' +
    '\n' +
    '\n' +
    '> Build failed because of webpack errors',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

  32s › app › Error: Command failed with exit code 1: node_modules/.bin/next build
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
Failed to compile.

./node_modules/next/dist/compiled/@vercel/nft/LICENSE
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Copyright 2019 Vercel, Inc.
| 
| Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

Import trace for requested module:
./node_modules/next/dist/compiled/@vercel/nft/ sync ^\.\/.*$
./node_modules/next/dist/compiled/@vercel/nft/index.js
./node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js
./node_modules/next/dist/build/webpack-config.js
./node_modules/next/dist/server/dev/hot-reloader.js
./node_modules/next/dist/server/dev/next-dev-server.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

./node_modules/next/dist/compiled/webpack/bundle5.js:141344:0
Module not found: Can't resolve 'next/dist/build/webpack/plugins/terser-webpack-plugin'

Import trace for requested module:
./node_modules/next/dist/compiled/webpack/webpack.js
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:9:0
Module not found: Can't resolve 'webpack5/lib/javascript/BasicEvaluatedExpression'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:11:0
Module not found: Can't resolve 'webpack5/lib/ModuleFilenameHelpers'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found

./node_modules/next/dist/compiled/webpack/webpack.js:13:0
Module not found: Can't resolve 'webpack5/lib/node/NodeTargetPlugin'

Import trace for requested module:
./node_modules/next/dist/server/config-utils.js
./node_modules/next/dist/server/config.js
./node_modules/next/dist/server/next.js
./node_modules/@sentry/nextjs/dist/utils/instrumentServer.js
./node_modules/@sentry/nextjs/dist/index.server.js
./sentry.server.config.js

https://nextjs.org/docs/messages/module-not-found


> Build failed because of webpack errors
info  - Loaded env from /Users/janklan/dev/website/.env.local
info  - Loaded env from /Users/janklan/dev/website/.env
info  - Checking validity of types...
info  - Creating an optimized production build...
```

Running `node_modules/.bin/next build` manually builds the app with no errors.

I'm not sure if/how is all this relevant, but I do hope it helps!

**Comment by mathiasfc** [comment]
As a temporary fix, I just installed [serverless](https://github.com/serverless/serverless/) locally on a version older than [3.0.0](https://github.com/serverless/serverless/releases/tag/v3.0.0) which has breaking changes. And apparently things started working again...

**Comment by richayles** [comment]
I have this same issue, is there a resolution to this?

**Comment by BrandonEscamilla** [comment]
Same here

**Comment by richayles** [comment]
So the main serverless repo upgraded to v3 with breaking changes, there is a blog post on it. I had the deployment as part of my ci flow and changed `npm install -g serverless` to `npm install -g serverless@2.72.2` and then my other commands worked as before. Temporary fix for the moment

**Comment by Sotatek-VuPhan** [comment]
> Try this to deploy:
> 
> ```
> npx serverless@2.72.2
> ```

thanks @ferdingler

**Comment by BrandonEscamilla** [comment]
Now I have this issue, any idea why?
![CleanShot 2022-02-08 at 15 05 08](https://user-images.githubusercontent.com/21966716/153007021-137ba6c6-0ee1-469d-a249-575587d0f0cc.png)
?

**Comment by Rafcin** [comment]
So is Serverless versions >=3 messed up for Next deployments? I use Aws Amplify to deploy and I hijack the serverless config with my own, it seems that deploying a Next app with just Next as a dependency works fine, however, if you start adding things like Sentry, Next/MDX then it throws the vercel/NFT/license error and fails to build. Is the current solution to use `2.72.2`?

**Comment by CervarlCG** [comment]
> So is Serverless versions >=3 messed up for Next deployments? I use Aws Amplify to deploy and I hijack the serverless config with my own, it seems that deploying a Next app with just Next as a dependency works fine, however, if you start adding things like Sentry, Next/MDX then it throws the vercel/NFT/license error and fails to build. Is the current solution to use `2.72.2`?

@Rafcin  Yes, currently the unique workaround is install serverless@2.72.2 as a dev dependecy

**Comment by Rafcin** [comment]
I'm just modified my config to use 2.72.2 so I'll see if it builds, I wonder if this has been the issue the whole time! I could never deploy with 12 and I always thought something with Next v >=12 or some of those packages caused these issues.

**Comment by kaamoss** [comment]
Now that AWS has cutoff support for the `aws:states:opt-out` workaround, and only serverless versions >= 3.5.3 work with lambda states per here https://github.com/serverless-nextjs/serverless-next.js/issues/1976 , is anyone else completely hosed on next serverless in AWS lambda too?

**Comment by uclaeamsavino** [comment]
We fixed the lambda states issue by upgrading Serverless Next from 1.18 to 3.6.0.

**Comment by kaamoss** [comment]
> We fixed the lambda states issue by upgrading Serverless Next from 1.18 to 3.6.0 in the serverless.yml file.

Thank you a ton for this @uclaeamsavino , this workaround is also functioning for us now.

**Comment by optydeviocourses** [comment]
# Soluction:

1. npm install global serverless version **2.7.2**
```
 npm install -g serverless@2.72.2
 sls -v
 ```
![Captura de Tela 2022-03-23 às 20 26 09](https://user-images.githubusercontent.com/66975293/159812785-3ab22fa8-d1b6-4c3c-847c-6f3b72109aa2.png)

2. In the **package.json**
```
"dependencies": {
    "@sls-next/aws-cloudfront": "3.6.0",
    "@sls-next/aws-lambda": "3.6.0",
    "@sls-next/aws-sqs": "^3.5.3",
    "@sls-next/domain": "^3.5.3",
    "@sls-next/serverless-component": "3.6.0",
    ...
}
```
3. In the file **serveless.yml**
```
next-new :
   component : "./node_modules/@sls-next/serverless-component"
```
4. Results
5.1 deploy for aws
```
sls 
```
![Captura de Tela 2022-03-23 às 20 18 11](https://user-images.githubusercontent.com/66975293/159812039-9affec3c-75ab-44c8-8eec-7b062c11bcf5.png)

```
sls --debug
```
![Captura de Tela 2022-03-23 às 20 30 33](https://user-images.githubusercontent.com/66975293/159813158-29c6c633-3ac3-4688-855b-16ce941b0afc.png)
![Captura de Tela 2022-03-23 às 20 28 38](https://user-images.githubusercontent.com/66975293/159813067-990766de-b3e1-4915-a69c-21d0b8f75a5f.png)

5.2 remove for aws
```
sls remove
```
![Captura de Tela 2022-03-23 às 20 21 04](https://user-images.githubusercontent.com/66975293/159812258-0f06f7eb-91e1-442a-96b1-5be3807d2796.png)

**Comment by SampaioLeal** [comment]
@janklan have you solved your issue with sentry and serverless? i'm having this too

**Comment by elad-maimon** [comment]
When is this expected to be fixed?
I've been using the workarounds here for some time but when my app gets more mature and with new requirements I hit new problems..

Is it an issue of Serverless of the Next component? Because according to the Serverless Components [README](https://github.com/serverless/components) `npm i -g serverless` should be enough to use the serverless CLI.

Also, installing the CLI locally and using the `components-v1` command does not allow passing any arguments to it, lakes documentation and overall feels weird and hacky.

Again, not sure where is the problem, whenever it is, if it's a bug I totally get it, but if it's a result of an intended separation of the framework from the CLI as I get from the error message then IMHO it wasn't thought thoroughly and should be rolled back and done in an "API first" approach.

Thanks for all the hard work everyone is putting in it!

**Comment by ravitejagullapudi** [comment]
Install the cli using, npm install -g @serverless/cli and then run components-v1

**Comment by martinjuhasz** [comment]
I'm also wondering what the path forward here would be?
Would be nice if one of the maintainers could shed some more light on how to handle the versioning and what the plan for the future is. from what i understand is that this package will basically never support the new components apis?

my way to go was the following:
```
npm i serverless@2.72.2 --save-dev
npm i @sls-next/serverless-component --save-dev
```
```
someProject:
  component: "./node_modules/@sls-next/serverless-component"
```
```
"scripts": {
    "deploy": "./node_modules/.bin/serverless"
  }
```

**Comment by fondberg** [comment]
@martinjuhasz thanks for sharing. I couldn't get anything to work.
What is missing to be able to run serverless 3?

**Comment by with-key** [comment]
omg.. 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/66957178/170635519-4d80c1e8-4b82-4994-aa5e-b01cb5b7194b.png">

What the hell is wrong with you?

**Comment by dphang** [comment]
Hey all,

I am sorry for the lack of activity recently…honestly I got busy with other personal interests and was having trouble with finding other long-term maintainers. For fully visibility, Yes currently this library has to use that specific old version of Serverless components since it’s still on the beta components, and there is definitely a lot of tech debt from this (the original maintainer started this library when it was still in beta and it wasn’t upgraded). At a previous time I had looked into it but IIRC the GA components had some major incompatibilities with (I think it was something to do with needing to have custom build deploy logic which at the time wasn’t compatible with GA components doing builds/deploys in the Serverless cloud?). 

Long term we definitely should upgrade, although an equally viable path is to use things like CDK or Terraform CDK to deploy (eg there are solutions like Serverless Stack that are well-funded that use AWS CDK this way - perhaps we can explore more collaboration with them), which we have as deployers for lambda@edge and lambda (more diy), or try to get out of maintaining AWS deploy logic if possible.

There is a budget for Serverless components upgrade ($1000) and more general funds (to the tune of around $1100), so if anyone is seriously interested to work on this, please join the slack (send an email to serverlessnextjs@gmail.com for an invite) and it may be worth your while as there are decent financial incentives which we can work out depending on how much time you want to spend. I currently don’t need the money myself and my time is quite limited these days, so I’m hoping for other core contributors…

there are also other long term things to fix such as how to better keep up with feature parity with Next.js (for example, running Next.js server instead of emulating the routing logic ourselves) so we don’t have constant bugs due to differing behavior. And of course other projects like bringing it to Azure/GCP etc (but I would prefer making this more stable first)

Thanks for reading.

**Comment by mohebifar** [comment]
This worked for me:

```
yarn add -D @serverless/cli
```

Then every time you want to deploy:
```
yarn components-v1
```

**Comment by TxusBlack** [comment]
Is there an npx serverless@... option for Next.js version 12.3.1? The version `serverless@2.72.3` is not supported.
