### ISSUE TITLE
"Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken" Error When Deploying

### ISSUE THREAD

**Issue by Alien10123** [serverless-nextjs/serverless-next.js#2399]
### Issue Summary

When I deploy my next js app I get the error "Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken".

### Actual behavior

When I deploy I get the error "Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken". Here is what I get when I use the debug  flag:
```

  DEBUG ─ Resolving the template's static variables.                                                                
  DEBUG ─ Collecting components from the template.                                                                  
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Deploying bucket bqik5ju-51a5qrv in region us-east-1.
  DEBUG ─ Checking if bucket bqik5ju-51a5qrv exists.

  error:
  Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken
    at ensureBucket (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/aws-s3/dist/utils.js:78:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AwsS3.default (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/aws-s3/dist/component.js:40:9)
    at async NextjsComponent.deploy (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/serverless-component/dist/component.js:213:31)
    at async fn (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/serverless.js:67:38)
    at async runComponents (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+cli@1.6.0/node_modules/@serverless/cli/src/index.js:222:17)

  3s › myNextApplication › Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken 
```. My serverless.yml file is:
```
myNextApplication:
  component: "@sls-next/serverless-component"
  inputs: 
    build: false
``` (I use `build: false` because in wsl I get some errors when building, but I can build in windows).

### Expected behavior

It should take some time and deploy my next js app to aws lambda@edge.

### Steps to reproduce

Just use serverless.yml config:
```
myNextApplication:
  component: "@sls-next/serverless-component"
  inputs: 
    build: false
```
. And then try to deploy.

### Screenshots/Code/Configuration/Logs

Logs with debug flag:
```
  DEBUG ─ Resolving the template's static variables.                                                                
  DEBUG ─ Collecting components from the template.                                                                  
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Deploying bucket bqik5ju-51a5qrv in region us-east-1.
  DEBUG ─ Checking if bucket bqik5ju-51a5qrv exists.

  error:
  Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken
    at ensureBucket (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/aws-s3/dist/utils.js:78:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AwsS3.default (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/aws-s3/dist/component.js:40:9)
    at async NextjsComponent.deploy (/home/click/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.7/node_modules/@sls-next/serverless-component/dist/component.js:213:31)
    at async fn (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+template@1.1.4/node_modules/@serverless/template/serverless.js:67:38)
    at async runComponents (/mnt/c/Users/samue/AppData/Roaming/npm/pnpm-global/5/node_modules/.pnpm/@serverless+cli@1.6.0/node_modules/@serverless/cli/src/index.js:222:17)

  3s › myNextApplication › Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken 
```

### Versions

- OS/Environment: Windows (doesn't work on wsl)
- @sls-next/serverless-component version: latest
- Next.js version: 12.1.0

### Checklist

- [✅] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [✅] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [✅] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by Alien10123** [comment]
I figured out it is a 403 error btw, and the bucket name is not taken

**Comment by MGough** [comment]
> I figured out it is a 403 error btw, and the bucket name is not taken

Hi @Alien10123 - Delayed response, and I'm not a contributor just a user of this library, I'd strongly suggest enabling AWS CloudTrail and re-running the deployment or checking your CloudTrail events if it's already enabled. This library only receives the details AWS return from their APIs, and their errors can be quite vague, while Cloudtrail will generally tell you specifically what failed.

**Comment by hwangm** [comment]
I got this error when I was using AWS credentials without the right S3 permissions...double check to make sure you have at least what is outlined in the readme here about S3 permissions
