### ISSUE TITLE
UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.DefaultCacheBehavior

### ISSUE THREAD

**Issue by myriky** [serverless-nextjs/serverless-next.js#2412]
### Issue Summary
3.7.0-alpha.5 is fine.
but over 3.7.0-alpha.6 build failed.

maybe I think this PR with related
https://github.com/serverless-nextjs/serverless-next.js/pull/2285
```
  error:
  MultipleValidationErrors: There were 6 validation errors:
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.DefaultCacheBehavior
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[0]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[1]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[2]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[3]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[5]
```
### Actual behavior
deploying failed.

### Expected behavior
just deployed.

### Steps to reproduce
here is serverless.yml config:

```
myApp:
  component: "@sls-next/serverless-component@3.7.0-alpha.12" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.11" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.10" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.9" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.8" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.7" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.6" // FAILED
  component: "@sls-next/serverless-component@3.7.0-alpha.5" // SUCCESS
````

### Screenshots/Code/Configuration/Logs
```
$ sls

  error:
  MultipleValidationErrors: There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.DefaultCacheBehavior
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[0]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[1]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[2]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[3]
    at ParamValidator.validate (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:40:28)
    at Request.VALIDATE_PARAMETERS (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/config.js:386:7)
    at /Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/config.js:404:9
    at SharedIniFileCredentials.get (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/config.js:398:24)
    at Config.getCredentials (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/config.js:418:9) {
  code: 'MultipleValidationErrors',
  errors: [
    UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.DefaultCacheBehavior
        at ParamValidator.fail (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validate (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/event_listeners.js:132:42)
        at Request.callListeners (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/sequential_executor.js:106:20) {
      code: 'UnexpectedParameter',
      time: 2022-03-18T16:48:15.070Z
    },
    UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[0]
        at ParamValidator.fail (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateList (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:103:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:90:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14) {
      code: 'UnexpectedParameter',
      time: 2022-03-18T16:48:15.070Z
    },
    UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[1]
        at ParamValidator.fail (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateList (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:103:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:90:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14) {
      code: 'UnexpectedParameter',
      time: 2022-03-18T16:48:15.070Z
    },
    UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[2]
        at ParamValidator.fail (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateList (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:103:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:90:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14) {
      code: 'UnexpectedParameter',
      time: 2022-03-18T16:48:15.070Z
    },
    UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[3]
        at ParamValidator.fail (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateList (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:103:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:90:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14)
        at ParamValidator.validateMember (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validateStructure (/Users/riky/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.6/node_modules/aws-sdk/lib/param_validator.js:75:14) {
      code: 'UnexpectedParameter',
      time: 2022-03-18T16:48:15.071Z
    }
  ],
  time: 2022-03-18T16:48:15.072Z
}

  94s › myApp › MultipleValidationErrors: There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.DefaultCacheBehavior
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[0]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[1]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[2]
* UnexpectedParameter: Unexpected key 'ResponseHeadersPolicyId' found in params.DistributionConfig.CacheBehaviors.Items[3]
```
### Versions

- OS/Environment: OS X 11.4 M1
- @sls-next/serverless-component version: serverless-component@3.7.0-alpha.6
- Next.js version: 12.0.10

### Checklist

- [v] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [v] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [v] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by myriky** [comment]
surprisingly, I made install components at localhost, it worked.

```
$ npm install @sls-next/serverless-component@3.7.0-alpha.9 @sls-next/aws-s3@3.7.0-alpha.9 @sls-next/aws-cloudfront@3.7.0-alpha.9 @sls-next/aws-sqs@3.7.0-alpha.9 @sls-next/aws-lambda@3.7.0-alpha.9 @sls-next/domain@3.7.0-alpha.9 @sls-next/cdk-construct@3.7.0-alpha.9 --save-dev
```

serverless.yml
```
myAPP:
  component: "./node_modules/@sls-next/serverless-component"
```

nevertheless, I couldn't find a clue 🤔

**Comment by webbster-dev** [comment]
This is still an issue on the latest release. Not sure what to do here, on 3.7.0-alpha.5 it works fine like @myriky mentioned.

**Comment by donald-lendit** [comment]
local 장비에서 테스트
- 3.8.0.alpha.0 **ok**
- 3.7.0 **ok**
- 3.7.0.alpha.5 **ok**

Github action 에서 테스트
- 3.8.0.alpha.0 failed
- 3.7.0 failed
- 3.7.0.alpha.5 **ok**

**Comment by donald-lendit** [comment]
Test on local machine
- 3.8.0.alpha.0 ok
- 3.7.0 ok
- 3.7.0.alpha.5 ok

Test in Github action
- 3.8.0.alpha.0 failed
- 3.7.0 failed
- 3.7.0.alpha.5 ok

**Comment by tlan16** [comment]
For people experiencing this issue, adding this to yarn resolution worked for me:
```json5
  "resolutions": {
    "aws-sdk": "2.1328.0"
  },
```
I'm using `"@sls-next/serverless-component": "^3.7.0",`
