### ISSUE TITLE
AccessDeniedException: null error when running serverless with active AWS credentials

### ISSUE THREAD

**Issue by nagmak** [serverless-nextjs/serverless-next.js#2416]
### Issue Summary
After deploying our app yesterday everything was working fine for about 12-20 hours. Today morning the whole team has been experiencing this error. We're unable to re-deploy the app, and there's not much more information than this `null` value. We even tried upgrading to the latest alpha with no change. 

We have admin access in AWS, and our roles have access to DynamoDB, CloudFront, Lambda, and everything else that is needed to run the app correctly.

```
  error:
  AccessDeniedException: null
    at Object.extractError (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nugget/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0-alpha.11/node_modules/@sls-next/aws-lambda/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'AccessDeniedException',
  time: 2022-03-29T16:48:41.486Z,
  requestId: 'e6e4ca3a-ff84-4922-ba5d-24ea7b4059ef',
  statusCode: 403,
  retryable: false,
  retryDelay: 25.58786510856832
}
```

### Actual behavior

After our app was deployed, close to 20hrs later, we noticed a 503 error in some pages. After this, we attempted to re-deploy the app and realized we were all running into AccessDeniedException: null errors. In our logs on CloudFront there isn't too much information either.

<img width="1430" alt="Screen Shot 2022-03-29 at 10 02 46 AM" src="https://user-images.githubusercontent.com/16668970/160666882-5bc92449-79ee-499f-8b7c-46819f6f9e57.png">

### Expected behavior
Expected to have either the app deployed and working or a more readable error to better understand why this is occurring. The current error is not providing enough information to move ahead.

### Steps to reproduce

our `serverless.yml`:

```
twali-xyz-staging:
  component: "@sls-next/serverless-component@3.7.0-alpha.12"
  inputs:
    policy: "arn:aws:iam::<ACCOUNT ID>:policy/<POLICY NAME>"
    roleArn: "arn:aws:iam::<ACCOUNT ID>:role/<ROLE NAME>"
    build:
      env:
        TABLE_NAME: "<DB NAME>"
```

Basically just running `serverless` as usual on our app, results in this new `AccessDeniedException: null` that never appeared before. 

### Screenshots/Code/Configuration/Logs

<img width="1013" alt="Screen Shot 2022-03-29 at 12 28 13 PM" src="https://user-images.githubusercontent.com/16668970/160692531-c9dd2692-4b0e-43f0-b764-ded2f5e7b50f.png">

### Versions

- OS/Environment: Macbook Pro v10.14.6, macOS Mojave
- @sls-next/serverless-component version: @sls-next/serverless-component@3.7.0-alpha.12
- Next.js version: 12.1.0

### Checklist

- [ ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by venuka-explorelogy** [comment]
I have this issue too

**Comment by pavlo-mais** [comment]
Same problem

**Comment by CMcDev** [comment]
Any update on this? I am running into the same issues.
