### ISSUE TITLE
TypeError: Unexpected MODIFIER at 70, expected END

### ISSUE THREAD

**Issue by mykm-o8** [serverless-nextjs/serverless-next.js#2433]
### Issue Summary & Actual behavior

In the middle of the `serverless` execution, the following error stack breaks the process.

### Expected behavior

Having dynamic routes in the nextjs application, be able to build the app using `serverless`.
Also we can't refrain from using dynamic routes.

### Versions

- OS/Environment: MacOS Monterey 12.3.1
- @sls-next/serverless-component version: 3.7.0
- Next.js version: 11.1.2

### Screenshots/Code/Configuration/Logs

```
Unable to convert path to regex: /api/files/[service-slug]/[product-group-slug]/[category-slug]/[...file-name]. Please check for any special characters. › Deploying ..

  error:
  TypeError: Unexpected MODIFIER at 70, expected END
    at mustConsume (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/path-to-regexp/dist/index.js:114:15)
    at parse (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/path-to-regexp/dist/index.js:173:9)
    at stringToRegexp (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/path-to-regexp/dist/index.js:331:27)
    at pathToRegexp (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/path-to-regexp/dist/index.js:405:12)
    at pathToRegexStr (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/core/dist/build/pathToRegexStr.js:21:50)
    at /Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/core/dist/build/index.js:95:64
    at Array.forEach (<anonymous>)
    at prepareBuildManifests (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/core/dist/build/index.js:65:35)
    at Builder.build (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/lambda-at-edge/dist/build.js:389:101)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NextjsComponent.build (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/serverless-component/dist/component.js:165:13)
    at async NextjsComponent.default (/Users/user/.serverless/components/registry/npm/@sls-next/serverless-component@3.7.0/node_modules/@sls-next/serverless-component/dist/component.js:22:13)
    at async fn (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/serverless.js:67:38)
    at async Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:220:17)

  82s › myapp › TypeError: Unexpected MODIFIER at 70, expected END
```

**Comment by PSoltes** [comment]
I did some digging in this package and the issue appears to be that `/api/files/[service-slug]/[product-group-slug]/[category-slug]/[...file-name]` route is converted by function `expressifyDynamicRoute` to the path `/api/files/:service-slug/:product-group-slug/:category-slug/:file-name*`. And this path cannot be converted by `path-to-regexp` due to asterisk (*) at the end. Is this correct behaviour or bug?

**Comment by PSoltes** [comment]
I got solution from here https://github.com/pillarjs/path-to-regexp/issues/278 it turns out dashes in variables in some cases do not work. It would be great to add this somewhere into docs of @sls-next, cause next allows dashes in path variables

**Comment by mykm-o8** [comment]
The solution to this was replacing dashes with underscores in route names.
/api/files/[service-slug]/[product-group-slug]/[category-slug]/[...file-name]
to
/api/files/[service_slug]/[product_group_slug]/[category_slug]/[...file_name]
