### ISSUE TITLE
503 ERROR The request could not be satisfie - Cannot find module 'next/dist/compiled/node-fetch'\

### ISSUE THREAD

**Issue by alirezavlz** [serverless-nextjs/serverless-next.js#2452]
It seems 503 is a pretty usual error, In my case I get this one:

### Screenshots/Code/Configuration/Logs
```json
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'next/dist/compiled/node-fetch'\nRequire stack:\n- /var/task/pages/_error.js\n- /var/task/default-handler-0a0dc009.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module 'next/dist/compiled/node-fetch'",
    "Require stack:",
    "- /var/task/pages/_error.js",
    "- /var/task/default-handler-0a0dc009.js",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:101:18)",
    "    at Object.9371 (/var/task/pages/_error.js:4563:18)",
    "    at __webpack_require__ (/var/task/webpack-runtime.js:25:42)",
    "    at Object.3634 (/var/task/pages/_error.js:4202:42)",
    "    at __webpack_require__ (/var/task/webpack-runtime.js:25:42)",
    "    at Object.4336 (/var/task/pages/_error.js:34:94)",
    "    at __webpack_require__ (/var/task/webpack-runtime.js:25:42)"
  ]
}
```

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 3.7.0
- Next.js version: 12.0.6

**Comment by alirezavlz** [comment]
After investigation it seems `node_modules` is not part of the .zip file, is there any solution to force include node_modules in the app with having `nextDistDir`?

**Comment by Surk217** [comment]
any solutions?

**Comment by alirezavlz** [comment]
@Surk217 I had to restructure my directories in project.
