### ISSUE TITLE
Support logging of request context when there's an exception in default-handler

### ISSUE THREAD

**Issue by dhruvrajvanshi** [serverless-nextjs/serverless-next.js#2464]
**Is your feature request related to a problem? Please describe.**
Right now, any time there's an exception in the default-handler, we only get a stack, trace, and not anything else to go by.

For example, here's a trace that we see in production frequently.

```
ERROR	Invoke Error 	
{
"errorType": "URIError",
"errorMessage": "URI malformed",
"stack": [
"URIError: URI malformed",
"    at decodeURI (<anonymous>)",
"    at handlePublicFiles (/var/task/default-handler-dca9fd08.js:1689:24)",
"    at routeDefault (/var/task/default-handler-dca9fd08.js:1725:24)",
"    at handleDefault (/var/task/default-handler-dca9fd08.js:1830:25)",
"    at handleOriginRequest (/var/task/default-handler-dca9fd08.js:101775:25)",
"    at Runtime.handler (/var/task/default-handler-dca9fd08.js:101702:26)",
"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
]
}
```
As you can see, the stack trace is there, but nothing else.

**Describe the solution you'd like**
Would like to handle exceptions in the handlers, and log out the request context (URL, method, etc) in the default handler function.

**Describe alternatives you've considered**
Logging is just a specific thing, it would be nice to have a general way to hook into the built code, so that we could run arbitrary functions on specific events, like `beforeRequest`, `afterResponse`, `onError`. Some way to register callbacks for these would be nice. If these were provided, we could use them to write our own logging logic.

**Additional context**
If this is an acceptable change, I can open a PR.

**Comment by dhruvrajvanshi** [comment]
I was thinking something along the lines of [this](https://github.com/dhruvrajvanshi/serverless-next.js/commit/990ca45508988962cc8f7850e0a63d710ade5b92).
I'm happy to open a PR in case this approach is acceptable.

**Comment by naruthk** [comment]
+1

Having the same problem too.
