### ISSUE TITLE
all revalidation options trigger 503 error

### ISSUE THREAD

**Issue by rares-lupascu** [serverless-nextjs/serverless-next.js#2485]
### Issue Summary

trying to most basic implement ISR On Demand ... nothing dynamic just the secret ... revalidation
all good locally ... once deployed to AWS i get
```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```
i think it is actually crashing at
```
await res.revalidate('/');
```
also i manually assigned admin access to lambda's role and redeployed ...same output
also turned on revalidation after 60s returning this in the props of getStaticProps
```
return {
    props: {
        model: null,
    },
    revalidate: 60,
};
```

### Actual behavior

see above

### Expected behavior

ISR on demand

### Steps to reproduce

create revalidate.js with this content
```
export default async function handler(req, res) {
    if (
        req.query.secret !== process.env.REVALIDATION_SECRET
    ) {
        return res.status(401).json({message: 'Goodbye'});
    }

    return res.send({revalidated: true});
 }
```

### Screenshots/Code/Configuration/Logs

```
xxx:
  component: "@sls-next/serverless-component@3.7.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    memory: 4096
    timeout: 30
    cloudfront:
      # this is the default cache behaviour of the cloudfront distribution
      # the origin-request edge lambda associated to this cache behaviour does the pages server side rendering
      defaults:
        defaultTTL: 86400
        forward:
          headers:
            [
              Origin,
              Referer,
              Host
            ]
```
cloudwatch logs
```
2022-08-28T21:53:23.029Z	5651d2ad-c7c3-4fe0-8a2e-4368e8749715	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Failed to revalidate /: Invariant: required internal revalidate method not passed to api-utils",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Failed to revalidate /: Invariant: required internal revalidate method not passed to api-utils",
        "stack": [
            "Error: Failed to revalidate /: Invariant: required internal revalidate method not passed to api-utils",
            "    at revalidate (/var/task/chunks/1458.js:2854:15)",
            "    at Stream.apiRes.revalidate (/var/task/chunks/1458.js:2788:46)",
            "    at handler (/var/task/pages/api/revalidate.js:172:15)",
            "    at Object.apiResolver (/var/task/chunks/1458.js:2797:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
            "    at async Module.<anonymous> (/var/task/chunks/1458.js:123:13)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Failed to revalidate /: Invariant: required internal revalidate method not passed to api-utils",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

### Versions

- @sls-next/serverless-component version: 3.7.0
- Binaries:
Node: 14.17.5
npm: 6.14.14
Yarn: 3.2.3
pnpm: N/A
- Relevant packages:
next: 12.2.5
eslint-config-next: 12.2.5
react: 18.2.0
react-dom: 18.2.0

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by rares-lupascu** [comment]
this is the part of the code generating the error
```
try {
        console.log({context})
        if (context.trustHostHeader) {
            const res = await fetch(`https://${req.headers.host}${urlPath}`, {
                method: "HEAD",
                headers: {
                    ...revalidateHeaders,
                    cookie: req.headers.cookie || ""
                }
            });
            // we use the cache header to determine successful revalidate as
            // a non-200 status code can be returned from a successful revalidate
            // e.g. notFound: true returns 404 status code but is successful
            const cacheHeader = res.headers.get("x-vercel-cache") || res.headers.get("x-nextjs-cache");
            if ((cacheHeader == null ? void 0 : cacheHeader.toUpperCase()) !== "REVALIDATED" && !(res.status === 404 && opts.unstable_onlyGenerated)) {
                throw new Error(`Invalid response ${res.status}`);
            }
        } else if (context.revalidate) {
            const { req: mockReq , res: mockRes , streamPromise ,  } = (0, _mockRequest).mockRequest(urlPath, revalidateHeaders, "GET");
            await context.revalidate(mockReq, mockRes);
            await streamPromise;
            if (mockRes.getHeader("x-nextjs-cache") !== "REVALIDATED" && !(mockRes.statusCode === 404 && opts.unstable_onlyGenerated)) {
                throw new Error(`Invalid response ${mockRes.statusCode}`);
            }
        } else {
            throw new Error(`Invariant: required internal revalidate method not passed to api-utils`);
        }
    } catch (err) {
        throw new Error(`Failed to revalidate ${urlPath}: ${(0, _isError).default(err) ? err.message : err}`);
    }
```

**Comment by rares-lupascu** [comment]
the context in the first if looks like this
```
context: {
    previewModeId: '4b8...',
    previewModeSigningKey: '9e6...',
    previewModeEncryptionKey: '0ec...'
  }
```

**Comment by rares-lupascu** [comment]
had to give up on [serverless-next.js](https://github.com/serverless-nextjs/serverless-next.js) ... i hope i was the only one to encounter this ... if not ... good luck :)

**Comment by HiroYuan-DAICHIGP** [comment]
no update for this?

**Comment by OSonntag** [comment]
Yes the execution role for the lambda function that generates the incremental builds has no permission to use the SQS service. This is needed:

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/55790463/221380781-086b2e15-333a-4b97-abaf-0e6e8834115b.png">

For I cvhanged the policy to include an inline policy with access to all sqs operations
