### ISSUE TITLE
serverless can't find package from a pinned version

### ISSUE THREAD

**Issue by ivanpetrushev** [serverless-nextjs/serverless-next.js#490]
**Describe the bug**
According to [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md#getting-started) we must pin the serverless-next.js version like:
```
myNextApplication:
  component: "@sls-next/serverless-component@{version_here}"
```

However, from some time ago pinning version doesn't work. Last I was able to pin:
>  component: "serverless-next.js@1.9.5"

And after this something in the package name changed (serverless-next.js => @sls-next/serverless-component) and the new name is not reachable anymore.

**To Reproduce**
Set this in serverless.yml:
```
prj:
  component: "@sls-next/serverless-component@{1.15.0-alpha.5}"
```

> serverless --debug

```

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.

  error:
  Error: Component "@sls-next/serverless-component@{1.15.0-alpha.5}" was not found on NPM nor could it be resolved locally.
    at /usr/local/share/.config/yarn/global/node_modules/@serverless/core/src/utils/download.js:97:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

  0s › Template › Error: Component "@sls-next/serverless-component@{1.15.0-alpha.5}" was not found on NPM nor could it be resolved locally.
```

**Expected behavior**
If there was a change, I assume https://www.npmjs.com/package/@sls-next/serverless-component/v/1.15.0-alpha.5 this should be the new latest package?

**Desktop:**

- OS: Debian
- Version 9

**Comment by ivanpetrushev** [comment]
Silly me... "@sls-next/serverless-component@1.15.0-alpha.5" != "@sls-next/serverless-component@{1.15.0-alpha.5}"
