### ISSUE TITLE
ERR! code ENOLOCAL when trying to deploy

### ISSUE THREAD

**Issue by gullerg** [serverless-nextjs/serverless-next.js#550]
**Describe the bug**
```
I get an ERR! code ENOLOCAL when I try to deploy my Next.js app using serverless-next.js.
error:
  { Error: Command failed: npm install serverless-next.js@1.15.0-alpha.2 --prefix C:\Users\firstname lastname\.serverless\components\registry\npm\serverless-next.js@1.15.0-alpha.2
npm ERR! code ENOLOCAL
npm ERR! Could not install from "lastname\.serverless\components\registry\npm\serverless-next.js@1.15.0-alpha.2" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\firstname lastname\AppData\Roaming\npm-cache\_logs\2020-08-16T17_02_00_318Z-debug.log

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'npm install serverless-next.js@1.15.0-alpha.2 --prefix C:\\Users\\firstname lastname\\.serverless\\components\\registry\\npm\\serverless-next.js@1.15.0-alpha.2',
  stdout: '',
  stderr:
   'npm ERR! code ENOLOCAL\nnpm ERR! Could not install from "lastname\\.serverless\\components\\registry\\npm\\serverless-next.js@1.15.0-alpha.2" as it does not contain a package.json file.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\firstname lastname\\AppData\\Roaming\\npm-cache\\_logs\\2020-08-16T17_02_00_318Z-debug.log\n' }
```
I'm not sure if this is a serverless-next.js issue or if it's an issue with my operating system (space in user folder, say). However, I don't face this issue with other global installs, so it's not entirely clear to me that this is an OS issue. Any ideas?

**To Reproduce**
Configure serverless in serverless.yml and run `serverless`

**Expected behavior**
The AWS resources are created correctly

**Desktop (please complete the following information):**

- Windows
- 10

**Comment by danielcondemarin** [comment]
Try using 

```yml
component: "@sls-next/serverless-component@1.16.0" 
```

Or if you want latest features in dev try an alpha version from https://www.npmjs.com/package/@sls-next/serverless-component

**Comment by gullerg** [comment]
I encounter the same issue, and I suspect that it might be because `serverless` is not executing in the right directory - is the build supposed to be located in the same directory as the command is executed in?

**Comment by MR-Neto** [comment]
I am having the same problem on windows. If I reproduce the steps in mac, no problem. 


```
 2s » Template » Error: Command failed: npm install @sls-next/serverless-component@1.17.0 --prefix C:\Users\Miguel Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel Neto\AppData\Roaming\npm-cache --global\_logs\2020-10-07T21_47_58_120Z-debug.log

```
