### ISSUE TITLE
Build fails if next-compose-plugins is used to wrap next.config.js

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#568]
**Describe the bug**
Some Next apps may use `next-compose-plugins` to have a clean way to compose multiple plugins like image optimization, offline capabilities, etc. See: https://github.com/cyrilwanner/next-compose-plugins

It seems that `@sls-next/1.17.0-alpha.6` broke this behavior but it is working in previous version `@sls-next/1.17.0-alpha.5`. When building, you will get an error like below:

```
  error:
  TypeError: Cannot destructure property 'defaultConfig' of 'undefined' as it is undefined.
    at /Users/danielphang/IdeaProjects/web-app/node_modules/next-compose-plugins/lib/index.js:18:3
    at Builder.<anonymous> (/Users/danielphang/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0-alpha.6/node_modules/@sls-next/lambda-at-edge/dist/build.js:243:64)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/danielphang/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0-alpha.6/node_modules/@sls-next/lambda-at-edge/dist/build.js:5:58)
```

I believe this happens because of my previous change to read `trailingSlash` from `next.config.js` to support trailing slash redirects: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L363-L365

When `next-compose-plugins` is used, `withPlugins` will return a function but this code will execute the config as function without any arguments and `next-compose-plugin` throws an error because it expects default config object to exist, which normally it does in here: https://github.com/vercel/next.js/blob/master/packages/next/next-server/server/config.ts#L214

Other plugins may face the same issue if they do not handle `undefined` config object.

**To Reproduce**

Here's a repro app: https://github.com/dphang/nextjs-repros/tree/next-compose-plugin-issue with `1.17.0-alpha.6` that is broken, and the steps are below as well:

1. Update `next.config.js` with `next-compose-plugins` e.g:

```ts
const withPlugins = require('next-compose-plugins');

module.exports = withPlugins([], {
  target: 'serverless',
  trailingSlash: true
});
```

2. Deploy using `@sls-next/1.17.0-alpha.7` or `@sls-next/1.17.0-alpha.6`

3. You will get error like below:

```
  error:
  TypeError: Cannot destructure property 'defaultConfig' of 'undefined' as it is undefined.
    at /Users/danielphang/IdeaProjects/web-app/node_modules/next-compose-plugins/lib/index.js:18:3
    at Builder.<anonymous> (/Users/danielphang/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0-alpha.6/node_modules/@sls-next/lambda-at-edge/dist/build.js:243:64)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/danielphang/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0-alpha.6/node_modules/@sls-next/lambda-at-edge/dist/build.js:5:58)
```

**Expected behavior**

Build should succeed.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Mac OS 10.15.5
- Version: @sls-next/1.17.0-alpha.6 or @sls-next/1.17.0-alpha.7

**Additional context**

I'm working on a PR to fix this case I hadn't caught earlier, just discovered this as I was trying to add `next-compose-plugins` just today. It looks like we can fix this by either:

1. Use Next's `loadConfig()` function which will return proper config as an object. It passes in default config object:

```js
{
  env: [],
  webpack: null,
  webpackDevMiddleware: null,
  distDir: '.next',
  assetPrefix: '',
  configOrigin: 'default',
  useFileSystemPublicRoutes: true,
  generateBuildId: [Function: generateBuildId],
  generateEtags: true,
  pageExtensions: [ 'tsx', 'ts', 'jsx', 'js' ],
  target: 'serverless',
  poweredByHeader: true,
  compress: true,
  devIndicators: { buildActivity: true, autoPrerender: true },
  onDemandEntries: { maxInactiveAge: 60000, pagesBufferLength: 2 },
  amp: { canonicalBase: '' },
  basePath: '',
  sassOptions: {},
  trailingSlash: true,
  experimental: {
    cpus: 11,
    modern: false,
    plugins: false,
    profiling: false,
    sprFlushToDisk: true,
    reactMode: 'legacy',
    workerThreads: false,
    pageEnv: false,
    productionBrowserSourceMaps: false,
    optimizeFonts: false,
    optimizeImages: false,
    scrollRestoration: false
  },
  future: { excludeDefaultMomentLocales: false },
  serverRuntimeConfig: {},
  publicRuntimeConfig: {},
  reactStrictMode: false
}
```

Though this requires adding `next` as a dependency.

2. Inspired by the above, we can avoid adding `next` as dependency and just update the `nextConfig()` line to:

```ts
nextConfig("phase-production-build", {}).trailingSlash ?? false;
```

This will also respect phases, i.e it will take config only meant for production build phase (vs. dev server etc). See docs here: https://nextjs.org/docs/api-reference/next.config.js/introduction where it gives function example as:

```js
module.exports = (phase, { defaultConfig }) => {
  return {
    /* config options here */
  }
}
```

Phases reference: https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/constants.ts#L1-L4

PS: I'm not sure why the bug repros in `1.17.0-alpha.6` in addition to `alpha.7` as this change should have been only published in `1.17.0-alpha.7`?

**Comment by dphang** [comment]
Have created PR to fix this here: https://github.com/serverless-nextjs/serverless-next.js/pull/569
