### ISSUE TITLE
CloudFront input failed validation. Could not find next.js pages for "distributionId"

### ISSUE THREAD

**Issue by etc-tiago** [serverless-nextjs/serverless-next.js#619]
**My configuration**
```yml
myNextApp:
  component: "@sls-next/serverless-component@1.16.0"
  inputs:
    name: register-site
    cloudfront:
      distributionId: "E38AYX5LCN3326"
    memory: 512
    timeout:
      defaultLambda: 15
      apiLambda: 10
```

**Describe the bug**
When deploying a Next.js application to AWS, the distributionId is not recognized.

**To Reproduce**

1. I created a deploy without having CloudFormation created, with full permission (for testing ...)
2. The CloudFront created resulted in the distribution E38AYX5LCN3326
3. I changed the configuration in Cloudless serverless.yml and deployed it again

```
  error:
  Error: CloudFront input failed validation. Could not find next.js pages for "distributionId,region,enabled"
    at NextjsComponent.validatePathPatterns (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.16.0/node_modules/@sls-next/serverless-component/dist/component.js:86:19)
    at NextjsComponent.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.16.0/node_modules/@sls-next/serverless-component/dist/component.js:267:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.16.0/node_modules/@sls-next/serverless-component/dist/component.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**
```yml
myNextApp:
  component: "@sls-next/serverless-component@1.16.0"
  inputs:
    name: register-site
    cloudfront:
      distributionId: "E38AYX5LCN3326"
    memory: 512
    timeout:
      defaultLambda: 15
      apiLambda: 10
```

**Desktop (please complete the following information):**
- Github Workflow
- Ubuntu Latest

**Comment by dphang** [comment]
Can you please try using the latest alpha (1.17 alpha 16), that change for `distributionId` is newer than the version you are using (1.16.0)

**Comment by etc-tiago** [comment]
Works with the latest alpha version (1.17 alpha 16)! Thank you
