### ISSUE TITLE
Can't resolve 'jimp'

### ISSUE THREAD

**Issue by Mair** [serverless-nextjs/serverless-next.js#643]
### Describe the bug
Error when running serverless. error on deployment step

### Actual behavior
```
  33s » learn-course » Error: Command failed with exit code 1: node_modules/.bin/next build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'jimp' in 'C:\projects\learn-course\learn-course\node_modules\@ampproject\toolbox-optimizer\lib\transformers'
```

### Expected behavior
successful deployment

- OS/Environment:
windows 10

### Additional context
my assumption is that I'm using 

"@aws-amplify/auth": "^3.3.1",
"@aws-amplify/core": "^3.4.2",

as dependencies and that I need to configure something in webpack for it to work. but not sure where to start
```
> Build error occurred
Error: > Build failed because of webpack errors
    at build (C:\projects\learn-course\learn-course\node_modules\next\dist\build\index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
info  - Loaded env from C:\projects\learn-course\learn-course\.env.local
info  - Creating an optimized production build...
info  - Using external babel configuration from C:\projects\learn-course\learn-course\.babelrc
    at makeError (C:\Users\mairs\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\@sls-next\serverless-component\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\mairs\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\@sls-next\serverless-component\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
  command: 'node_modules/.bin/next build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'info  - Loaded env from C:\\projects\\learn-course\\learn-course\\.env.local\n' +
    'info  - Creating an optimized production build...\n' +
    'info  - Using external babel configuration from C:\\projects\\learn-course\\learn-course\\.babelrc',
  stderr: 'Failed to compile.\n' +
    '\n' +
    "ModuleNotFoundError: Module not found: Error: Can't resolve 'jimp' in 'C:\\projects\\learn-course\\learn-course\\node_modules\\@ampproject\\toolbox-optimizer\\lib\\transformers'\n" +
    '\n' +
    '\n' +
    '> Build error occurred\n' +
    'Error: > Build failed because of webpack errors\n' +
    '    at build (C:\\projects\\learn-course\\learn-course\\node_modules\\next\\dist\\build\\index.js:15:918)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Comment by nickpassarella** [comment]
@Mair I worked around this by adding `jimp` to my `npm` dependencies. I haven't looked into it further than that though.

**Comment by Mair** [comment]
@nickpassarella Thank you for the suggestion. Unfortunately I have tried that but I still get the error

**Comment by dphang** [comment]
I am not sure but `jimp` is not used in our dependencies at all, so I think it is not related to this component? So it might be some webpack config that isn't playing well with jimp somehow? Might be worth to ask in webpack or Next.js community maybe?
