### ISSUE TITLE
Fail to deploy component, npm error

### ISSUE THREAD

**Issue by MR-Neto** [serverless-nextjs/serverless-next.js#660]
### Describe the bug

I have followed the get started steps, however the component fails to deploy. I tried the same on my mac and it work. It may be a problem with windows.

### Steps to reproduce

1. `npx create-next-app`

1. `npx serverless create --template aws-nodejs`

1. Updated serveless.yml to:
```
myNextApp:
  component: "@sls-next/serverless-component@1.17.0"
```
4. `npx serverless`

### Screenshots/Code
```
  error:
  Error: Command failed: npm install @sls-next/serverless-component@1.17.0 --prefix C:\Users\Miguel Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel Neto\AppData\Roaming\npm-cache --global\_logs\2020-10-08T07_57_45_354Z-debug.log

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install @sls-next/serverless-component@1.17.0 --prefix C:\\Users\\Miguel Neto\\.serverless\\components\\registry\\npm\\@sls-next\\serverless-component@1.17.0',
  stdout: '',
  stderr: 'npm ERR! code ENOLOCAL\n' +
    'npm ERR! Could not install from "Neto\\.serverless\\components\\registry\\npm\\@sls-next\\serverless-component@1.17.0" as it does not contain a package.json file.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\Miguel Neto\\AppData\\Roaming\\npm-cache --global\\_logs\\2020-10-08T07_57_45_354Z-debug.log\n'
}

  4s » Template » Error: Command failed: npm install @sls-next/serverless-component@1.17.0 --prefix C:\Users\Miguel Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel Neto\AppData\Roaming\npm-cache --global\_logs\2020-10-08T07_57_45_354Z-debug.log
```

- OS/Environment:
@sls-next/serverless-component@1.17.0
Windows 10

**Comment by dphang** [comment]
Unfortunately I'm using Mac OS for development, so can't actually debug it.

Perhaps try checking `Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0` and see if it's the package is installed correctly? Maybe there is a bad install so you might need to delete its contents so that Serverless can pick it up. It should have a `package.json` similar to below. For example, if i use npm to manually install it on my Mac, it should look like below:

```
npm install -g @sls-next/serverless-component@1.17.0 
```zsh
danielphang@Daniels-MBP serverless-component % pwd
/usr/local/lib/node_modules/@sls-next/serverless-component
danielphang@Daniels-MBP serverless-component % ls
CHANGELOG.md		__mocks__		dist			package.json		tsconfig.build.json	yarn-error.log
LICENSE			arch.png		logo.gif		serverless.js		tsconfig.json
README.md		arch_no_grid.png	node_modules		src			types.d.ts
danielphang@Daniels-MBP serverless-component % 
```

**Comment by samir-araujo** [comment]
Had the same problem and could only solve with a simple workaround.

Just create an empty folder within the same path as the `--prefix` of `npm install`.
In your case you would need to create this folder `C:\Users\Miguel Neto\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0`

After this you can run `serverless` again and it should work

**Comment by jonahallibone** [comment]
After upgrading my local environment to npm 7.x I am having the same issue. As mentioned above I had to 
`mkdir /Users/jonah/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.16`
to get it working. Is there any reason for this?

**Comment by wavrin** [comment]
Followed the advice of @samir-araujo and it worked for me. Created empty folder at `.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0` and was able to run `npx serverless` successfully. Thanks.

**Comment by dphang** [comment]
Hm, not quite sure what the reason is unfortunately, might be bugginess of Serverless components beta we are still using. Unfortunately due to lack of resourcing I don't think anyone started on it. Was planning to get more help on it in Q1 2021 (there is also a financial incentive)

If the workarounds suffice maybe we can post it in the FAQs and just close this issue since there is no easy fix for it.

**Comment by dphang** [comment]
Closing since there is a workaround as mentioned above.

**Comment by callum-p** [comment]
I'm having this issue on Ubuntu. Making the directory doesn't seem to help. The plugin just removes it:
```sh
user@l0calhost:~/repos/personal/xxx.io$ mkdir "/home/user/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0"
user@l0calhost:~/repos/personal/xxx.io$ ls -la /home/user/.serverless/components/registry/npm/@sls-next/ 
total 12
drwxrwxr-x 3 user user 4096 Jun  7 10:48 .
drwxrwxr-x 3 user user 4096 Jun  7 10:33 ..
drwxrwxr-x 2 user user 4096 Jun  7 10:48 serverless-component@1.19.0
user@l0calhost:~/repos/personal/xxx.io$ serverless

  error:
  Error: Command failed: npm install @sls-next/serverless-component@1.19.0 --prefix /home/user/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm install @sls-next/serverless-component@1.19.0 --prefix /home/user/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0',
  stdout: '',
  stderr: ''
}

  6s › Template › Error: Command failed: npm install @sls-next/serverless-component@1.19.0 --prefix /home/user/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0


user@l0calhost:~/repos/personal/xxx.io$ ls -la /home/user/.serverless/components/registry/npm/@sls-next/ 
total 8
drwxrwxr-x 2 user user 4096 Jun  7 10:49 .
drwxrwxr-x 3 user user 4096 Jun  7 10:33 ..
user@l0calhost:~/repos/personal/xxx.io$ 
```
