### ISSUE TITLE
CloudFront attributes don't support dynamic variable interpolation

### ISSUE THREAD

**Issue by damo78** [serverless-nextjs/serverless-next.js#676]
### Describe the bug

When attempting to use variables for the `inputs.cloudfront` I receive a `BadRequest: null error`, whereas other parts of the component handle this okay, e.g. `name`, `description` etc..

```
org: example-org
app: domaincom
name: example-app
stage: dev
domain: 'example.com'
fullDomain: ${stage}.${domain}
distribution: E7A31AEXAMPLE

serverless-nextjs-app:
  component: '@sls-next/serverless-component@1.18.0-alpha.5'
  inputs:
    cloudfront:
      distributionId: ${distribution}
      aliases: ['${fullDomain}']
    description: '*lambda-type*@Edge for ${org}-${name}-${fullDomain}'
    name:
      defaultLambda: ${org}-${app}-${name}-${stage}-default-lambda
      apiLambda: ${org}-${app}-${name}-${stage}-api-lambda
```

### Actual behavior

`sls` results in:

```
{
  code: 'BadRequest',
  region: 'eu-west-1',
  time: 2020-10-14T14:19:04.161Z,
  requestId: '2897BB7D0E8200F2',
  extendedRequestId: 'yOtbWxEUzzXzZ/ElSPS4BOKV11wUrHQfnJ4zJtOEUgijQtjmHAoaOwvTkxxUWzADYwsY9/NyoEc=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 69.28260969435951
}

  8s › serverless-nextjs-app › BadRequest: null
```

### Expected behavior

When literals are used, the component deploys normally; there is no Bad Request.

### Steps to reproduce

Use variables in place of `inputs.cloudfront.distributionId` or `inputs.cloudfront.aliases` as examples.

### Screenshots/Code/Logs

```
$: sls --debug

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
info  - Creating an optimized production build...
info  - Collecting page data...
info  - Generating static pages (0/2)
info  - Finalizing page optimization...
  6s › serverless-nextjs-app › Deploying 
Page                                                           Size     First Load JS
┌ ○ /                                                          3.41 kB        62.3 kB
├   └ css/9a89afcbe95084ea8b90.css                             703 B
├   /_app                                                      0 B            58.9 kB
├ ○ /404                                                       3.44 kB        62.4 kB
└ λ /api/hello                                                 0 B            58.9 kB
+ First Load JS shared by all                                  58.9 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.51e263.js  10.9 kB
  ├ chunks/framework.cb05d5.js                                 39.9 kB
  ├ chunks/main.605a41.js                                      7.13 kB
  ├ chunks/pages/_app.60c4bf.js                                281 B
  ├ chunks/webpack.e06743.js                                   751 B
  └ css/6e9ef204d6fd7ac61493.css                               194 B

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

  DEBUG ─ Deploying bucket ep-eu-west-1-dev-tf-sls-nextjs-site-daklacouk-origin in region eu-west-1.
  DEBUG ─ Checking if bucket ep-eu-west-1-dev-tf-sls-nextjs-site-daklacouk-origin exists.

  error:
  BadRequest: null
    at Request.extractError (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/services/s3.js:680:35)
    at Request.callListeners (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/damo/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.5/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'BadRequest',
  region: 'eu-west-1',
  time: 2020-10-14T14:19:04.161Z,
  requestId: '2897BB7D0E8200F2',
  extendedRequestId: 'yOtbWxEUzzXzZ/ElSPS4BOKV11wUrHQfnJ4zJtOEUgijQtjmHAoaOwvTkxxUWzADYwsY9/NyoEc=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 69.28260969435951
}

  8s › serverless-nextjs-app › BadRequest: null
```

### Versions

- OS/Environment: macOS Catalina
- @sls-next/serverless-component version: 1.18.0-alpha.5
- Next.js version: 9.5.4

**Comment by damo78** [comment]
My apologies... after numerous further tests I found it was my AWS session that had expired so any variable that required an AWS interaction, it would cause the Bad Request.
