### ISSUE TITLE
"comment:"  input for Cloudfront is not working

### ISSUE THREAD

**Issue by LuisFros** [serverless-nextjs/serverless-next.js#694]
### Describe the bug
When adding custom inputs to the cloudfront distribution in `serverless.yml`, the option `"comment:"` fails with a validation error.
Serverless.yml
```
myNextApplication:
  component: '@sls-next/serverless-component@1.17.1-alpha.3'
  inputs:
    bucketName: ${env.BUCKET_NAME}
    cloudfront:
      comment: "Cloudfront comment"
      defaults:
        forward:
          headers: [Host]
```

### Actual behavior

```
  Error: CloudFront input failed validation. Could not find next.js pages for "comment"
    at NextjsComponent.validatePathPatterns (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:95:19)
    at NextjsComponent.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:305:18)
    at Generator.next (<anonymous>)
    at fulfilled (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  88s › myNextApplication › Error: CloudFront input failed validation. Could not find next.js pages for "comment"
```

### Expected behavior
For the deployment to be successful and `comment` be included in the distribution
### Steps to reproduce
- Add `comment` option inside `serverless.yml`, as  `cloudfront` options.
- If i remove the `comment` option, there is no issue to deploy the component.
### Screenshots/Code/Logs

```
  Error: CloudFront input failed validation. Could not find next.js pages for "comment"
    at NextjsComponent.validatePathPatterns (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:95:19)
    at NextjsComponent.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:305:18)
    at Generator.next (<anonymous>)
    at fulfilled (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.1-alpha.3/node_modules/@sls-next/serverless-component/dist/component.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  88s › myNextApplication › Error: CloudFront input failed validation. Could not find next.js pages for "comment"
```

### Versions

- OS/Environment: Linux
- @sls-next/serverless-component version: `@1.17.1-alpha.3`
- Next.js version: `9.5`

**Comment by dphang** [comment]
I believe `comment` cloudfront input is not implemented yet even in the latest alpha. By default that error message is shown because it assumes `comment` is a cache behavior for a page.

**Comment by dphang** [comment]
Fixed in latest alpha.

**Comment by LuisFros** [comment]
Thank you @dphang !!
