### ISSUE TITLE
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

### ISSUE THREAD

**Issue by lioaslan** [serverless-nextjs/serverless-next.js#739]
I have found an issue about this and found solution, but I don't understand why It don't work so I create new issue to describe more about error I met
### `next.config.js`
```javascript
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    });
    return config;
  },
  target: 'experimental-serverless-trace'
});
```
### `serverless.yml`
```
offshorevn-fe: 
  component: serverless-next.js@1.12.0-alpha.4
```
### When I run command `$ serverlesss` it showed:
```
  error:
  RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation
    at Object.extractError (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/leo/.serverless/components/registry/npm/serverless-next.js@1.12.0-alpha.4/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'RequestEntityTooLargeException',
  time: 2020-11-02T01:48:05.330Z,
  requestId: '407d7c26-c232-42eb-a403-53d435f8477f',
  statusCode: 413,
  retryable: false,
  retryDelay: 66.48187859031896
}

  134s › offshorevn-fe › RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation
```
### `package.json` 
```
    "@zeit/next-css": "^1.0.1",
    "next": "^9.1.1",
    "react": "^16.8.0",
    "webpack": "^4.41.3"
```
My project size is quite large, The size of folder `.serverless_nextjs` is ~600MB,

Thanks in advance,

**Comment by dphang** [comment]
Yes, this is mostly due to Lambda package size. You can read more here: https://github.com/serverless-nextjs/serverless-next.js#the-lambdaedge-code-size-is-too-large. I don't know your structure but if you have 100+ pages that all use server props or initial props, it could cause the large size.

Also, I am not sure about that component version, it is quite old so you should try the latest @sls-next/serverless-component 1.18.0. I think you need the new one to use the serverless-trace target. The latest version also remove unneeded pre-rendered pages JS if you don't have API routes. It might help there.

**Comment by lioaslan** [comment]
I tried ways you said but it still didn't work.
Maybe I should refactor and optimize my project. Thanks for your response
