### ISSUE TITLE
TypeError: Missing parameter name at 13

### ISSUE THREAD

**Issue by baj84** [serverless-nextjs/serverless-next.js#778]
Serverless.yml: 
```myNextApplication:
  component: '@sls-next/serverless-component@1.19.0-alpha.2'
```

I'm using nextjs 10. When I run `npx serverless` I get the following error:
```
TypeError: Missing parameter name at 13
    at lexer (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/path-to-regexp/dist/index.js:48:23)
    at parse (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/path-to-regexp/dist/index.js:98:18)
    at stringToRegexp (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/path-to-regexp/dist/index.js:331:27)
    at Object.pathToRegexp (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/path-to-regexp/dist/index.js:405:12)
    at Object.exports.default (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/lib/pathToRegexStr.js:4:46)
    at Object.entries.forEach (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:282:56)
    at Array.forEach (<anonymous>)
    at Builder.<anonymous> (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:251:43)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js:5:58)
```
Is someone able to point me in the right direction? Thanks!

**Comment by dphang** [comment]
Please post your `serverless.yml` and project structure, and `pages-manifest.json` in `.next/serverless` if possible.

It looks to be failing at around here in `build.js`:

``` ts
                else if (dynamicRoute) {
                    const route = expressRoute;
                    ssrPages.dynamic[route] = {
                        file: pageFile,
                        regex: pathToRegexStr_1.default(route)
                    };
                }
```

It seems that pathToRegex is not able to parse one of the dynamic routes in your project.

**Comment by baj84** [comment]
Thanks @dphang 

serverless.yml:
```
myNextApplication:
  component: '@sls-next/serverless-component@1.19.0-alpha.2'
  build:
    env:
      API_URL: 'https://bountiful-king-amanxbmwrno3.vapor-farm-c1.com/api'
```

pages-manigest.json:
```
  "/404": "pages/404.js",
  "/PublicPage": "pages/PublicPage.js",
  "/_error": "pages/_error.js",
  "/api/health-check": "pages/api/health-check.js",
  "/app/calendar": "pages/app/calendar.js",
  "/app/clients": "pages/app/clients.js",
  "/app/dashboard": "pages/app/dashboard.js",
  "/app/layout": "pages/app/layout.js",
  "/app/onboarding": "pages/app/onboarding.js",
  "/app/payments": "pages/app/payments.js",
  "/app/profile/[[...slug]]": "pages/app/profile/[[...slug]].js",
  "/app/settings": "pages/app/settings.js",
  "/forgot-password": "pages/forgot-password.js",
  "/home": "pages/home.js",
  "/login": "pages/login.js",
  "/reset-password": "pages/reset-password.js",
  "/successful-therapy-guide": "pages/successful-therapy-guide.js",
  "/therapist-signup": "pages/therapist-signup.js",
  "/therapist/[urlStub]/booking/[date]": "pages/therapist/[urlStub]/booking/[date].js",
  "/therapist/[urlStub]/booking/[date]/steps/account-details": "pages/therapist/[urlStub]/booking/[date]/steps/account-details.js",
  "/therapist/[urlStub]/booking/[date]/steps/appointment-details": "pages/therapist/[urlStub]/booking/[date]/steps/appointment-details.js",
  "/therapist/[urlStub]/booking/[date]/steps/check-email": "pages/therapist/[urlStub]/booking/[date]/steps/check-email.js",
  "/therapist/[urlStub]/booking/[date]/steps/confirmation-screen": "pages/therapist/[urlStub]/booking/[date]/steps/confirmation-screen.js",
  "/therapist/[urlStub]/booking/[date]/steps/payment-details": "pages/therapist/[urlStub]/booking/[date]/steps/payment-details.js",
  "/therapist/[urlStub]": "pages/therapist/[urlStub].js",
  "/therapists": "pages/therapists.js",
  "/verify-email": "pages/verify-email.js"
```

**Comment by dphang** [comment]
Ok, I think it is your optional catch-all `pages/app/profile/[[...slug]].js` which is not parsed properly. You can try the workaround here for now: https://github.com/serverless-nextjs/serverless-next.js/issues/523.

We will take a look at how to properly support this.

**Comment by baj84** [comment]
Thanks!

**Comment by dphang** [comment]
Cool, I'll close this and track it in the related issue. Thanks!
