### ISSUE TITLE
Cannot read property 'debug' 

### ISSUE THREAD

**Issue by morjanmihail** [serverless-nextjs/serverless-next.js#807]
Hello guys,
   I'm having the following error when I'm trying to remove the current deployment (using "sls remove"):

```
  TypeError: Cannot read property 'debug' of undefined
    at removeDomainFromCloudFrontDistribution (/Users/xxxxx/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/domain/utils.js:480:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Domain.remove (/Users/xxxxx/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/domain/serverless.js:209:9)

```

   I'm using the latest version of this component.

Thanks in advance,
Mihai

**Comment by dphang** [comment]
This was due to mismatched parameters, it was fixed in the latest alpha version.
