### ISSUE TITLE
TypeError: Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by apoorvmote** [serverless-nextjs/serverless-next.js#817]
### Describe the bug

on `sls remove` I get following error
```bash
error:
  TypeError: Cannot read property 'debug' of undefined
    at removeDomainFromCloudFrontDistribution (/home/apoorvmote/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/domain/utils.js:480:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Domain.remove (/home/apoorvmote/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/domain/serverless.js:209:9)

  10s › budgetApp › TypeError: Cannot read property 'debug' of undefined
```

### Expected behavior

I was hoping to remove the app from aws

### Steps to reproduce

- `npx create-next-app budget --use-npm`
- I change all jsx files to tsx and installed typescript as dev dependancy and `npm run dev` to initialize `tsconfig.json`
- `sls create -t aws-nodejs`
- add following in serverless yml
```yml
budgetApp:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    domain: mydomain.com
``` 
- `sls` to deploy to aws
- `sls remove` to delete the app

### Versions

- OS/Environment: Ubuntu 20.04 on WSL2
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.2

**Comment by dphang** [comment]
This was fixed in one of the 1.19 alpha versions, please try the latest and let me know if there are issues.
