### ISSUE TITLE
SyntaxError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by pbassut** [serverless-nextjs/serverless-next.js#846]
### Describe the bug
Looks like the tool doesn't play nice when you have an .env variable in the same folder you run `serverless`

### Actual behavior
It crashes with:
```
SyntaxError: Invalid left-hand side in assignment
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at hasCustomGetInitialProps (/Users/.../next/dist/build/utils.js:24:1064)
    at build (/Users/...node_modules/next/dist/build/index.js:15:2605)
Loaded env from /Users/.../.env
info  - Creating an optimized production build...
info  - Using external babel configuration from /Users/.../babel.config.js
info  - Collecting page data...
```

### Expected behavior
I would like for it to read my .env file. But if that's not possible, don't crash on me.

### Steps to reproduce
Just have a .env in your folder and run `serverless`

### Versions

- OS/Environment: OSX
- @sls-next/serverless-component version: 1.19.0-alpha.21
- Next.js version: Next.js v9.5.5

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by raslasarslas** [comment]
I have the same error, does anyone know how to solve it?

**Comment by pbassut** [comment]
Since the error is because of an environment file in the same folder you run (serverless delpoy), as a workaround, I found another way of setting my environment variables. Be creative in your setup and find your own.

**Comment by erodrig** [comment]
so one year and still nothing, strong community

**Comment by dphang** [comment]
Sorry it was missed, unfortunately I'm the only active maintainer right now (always looking for more!) and maintaining in my free time so I might miss some issues.

I could not repro the issue myself from steps above. @pbassut Do you have a minimal repro repo you can share? from the original stacktrace I couldn't see it erroring out in any code in this component (failure seems to originate from `next/dist/build/index.js`?)

**Comment by javiermanzano** [comment]
This issue save me A LOT of time.

Thanks @pbassut . I finally created a script to rename and recreate .env file on every deploy
