### ISSUE TITLE
Cannot deploy when CloudFront and S3 bucket already exists

### ISSUE THREAD

**Issue by huisang-growth** [serverless-nextjs/serverless-next.js#880]
### Describe the bug
When I specify an existing bucket name, serverless deploy results in 
`myLandingDev › AccessDenied: Access Denied`
**There is no way to integrate serverless deployment when I already have an existing S3 bucket and a CloudFront distribution in place, hosting current website.**

This is my serverless.yml:
```
myLandingDev:
  component: "@sls-next/serverless-component@1.19.0-alpha.28"
  inputs:
    domain: ["dev", "mysite.com"]
    domainRedirects:
      www.dev.mysite.com: https://dev.mysite.com
    bucketName: "dev.mysite.com"
    bucketRegion: "ap-northeast-2"
    roleArn: arn:aws:iam::*******:role/DeveloperRole
    description: "Lambda@Edge for myLandingDev"
    name: "myLandingDevLambda"
    runtime: "nodejs12.x"
    cloudfront:
      distributionId: "******* (my existing cloudfront distribution Id)"
    memory: 1024
    build:
      args: ["build"]
      env:
        NEXT_PUBLIC_ENV: "development"
```

**And this is my full error log:**
```
> npx serverless --debug

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
Loaded env from /**my-repo-directory**/.env
info  - Creating an optimized production build...
info  - Using external babel configuration from /**my-repo-directory**/package.json
info  - Collecting page data...
info  - Generating static pages (0/6)
info  - Generating static pages (1/6)
info  - Generating static pages (2/6)ng
info  - Generating static pages (4/6)
info  - Generating static pages (6/6)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          119 kB          193 kB
├   /_app                                                      0 B            60.4 kB
├ ○ /404                                                       2.37 kB        76.3 kB
├ ○ /email/error                                               5.68 kB        79.6 kB
├ ○ /email/success                                             5.67 kB        79.6 kB
├ ○ /flowchart/sample                                          57.7 kB         132 kB
├ λ /share/ending/[endingUid]                                  16.9 kB        97.4 kB
├ λ /share/story/[storyUid]                                    5.96 kB        86.5 kB
└ ○ /terms                                                     9.81 kB        70.2 kB
+ First Load JS shared by all                                  60.4 kB
  ├ chunks/6b370f778a0e26c3717288b9239efb379500a508.ca31a7.js  11.3 kB
  ├ chunks/framework.a97df1.js                                 40.2 kB
  ├ chunks/main.50415b.js                                      7.3 kB
  ├ chunks/pages/_app.340f61.js                                316 B
  ├ chunks/webpack.46fc7b.js                                   1.37 kB
  └ css/1c98ee31a9ebd4eb2f5a.css                               3.06 kB

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

  DEBUG ─ Deploying bucket dev.mysite.com in region ap-northeast-2.
  DEBUG ─ Checking if bucket dev.mysite.com exists.

  error:
  Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken
    at ensureBucket (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/@serverless/aws-s3/utils.js:53:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  26s › myLandingDev › Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken
```

### What I have done
- include "target: serverless" in next.config.js
- **delete .next, .serverless, .serverless-nextjs directory and deploy again**
- **add .env file in the same directory, containing correct AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY**
- make sure my package.json does not contain an existing @sls-next/serverless-component
- I have checked on my AWS console, and made sure that no files have been uploaded or altered in S3
- Use getServerSideProps correctly in the SSR-needed page
- deploy via command "npx serverless --debug"

Obviously, these efforts have not been successful.

**So this is the gist:**
### What should I do to integrate serverless & lambda if I already have an existing S3 and CloudFront in service?

-------

**And this is another related question** -- If I change the `bucketName` into a whole new string that does not collide with my existing S3, the `Error: Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken` error dissolves but another one appears, as below:

```
> npx serverless --debug

  DEBUG ─ Resolving the template's static variables.
  ... (same as above)
λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

  DEBUG ─ Deploying bucket ndev.mysite.com in region ap-northeast-2.
  DEBUG ─ Checking if bucket ndev.mysite.com exists.
  DEBUG ─ Bucket ndev.mysite.com does not exist. Creating...

  error:
  { AccessDenied: Access Denied
    at Request.extractError (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/hsyun/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.28/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2021-01-20T07:30:03.220Z,
  requestId: '7DCFB642335F9716',
  extendedRequestId:
   '27v4NFY3VHatDDxxHdOR5XYOdKOcdh2SALMboSsboJSsuNlQ7Bn0pQQ4E/0WjvDxODzNIBGK9ZI=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 34.3885514543786 }

  25s › myLandingDev › AccessDenied: Access Denied
```

My AWS role is adequate - I can go on AWS console and access S3, CloudFront, and Lambda.
### Hence my question - what access is causing this 403 error?

---

### Checklist

- [v] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [v] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by zerbinidamata** [comment]
I ran into the same issue, my "solution" until now is to let the plugin create a new Cloudfront distribution and config the path behaviors in the main Cloudfront config. It's working so far but there is a need to manually update your bucket policy since the plugin updates the policy in every deployment (the Cloudfronts behaviors are also updated so it will override any existing behaviors)

I would love to have a solution for this too 🤞

**Comment by amatyas001** [comment]
Hi, I solved the existing bucket issue by removing the bucket on each deploy. I'm using [Serverless S3 remover plugin](https://www.serverless.com/plugins/serverless-s3-remover) to do the work for me. Simply add this few new lines to  `serverless.yml`:

```yaml
plugins:
  serverless-s3-remover
custom:
  remover:
    buckets:
      insightbrowser-deploy-prod
```
This will take care of the existing bucket and the process can go on successfully. Hope it helps!

**Comment by huisang-growth** [comment]
@amatyas001 Thanks for the comment, but this is a serverless component, therefore plugins are not supported.

**Comment by huisang-growth** [comment]
I'm closing this issue.
Making a new S3 bucket with another name seems inevitable, and the AccessDenied error was a result of my IAM permission. I'm opening up another issue related to permission - 

```
DEBUG ─ Creating lambda dev-storyplay-serverless-default-lambda in the us-east-1 region.
  error:
  { AccessDeniedException: Cross-account pass role is not allowed.
```
Anyways this issue is closed. This so called "zero configuration" and "fast" component is not at all easy to onboard.
