### ISSUE TITLE
How to deploy Prod and Staged

### ISSUE THREAD

**Issue by msimonc** [serverless-nextjs/serverless-next.js#895]
Issue: on command line "sls" the .serverless folder caches data not overridden by the serverless.yml file.

result: prod is removed (website not found) when Staged is deployed.

workaround in package.json | scripts:
```
"prod": "rm -rf .serverless && cp sls-prod.yml serverless.yml && sls && rm serverless.yml",
"stage": "rm -rf .serverless && cp sls-stage.yml serverless.yml && sls && rm serverless.yml",
```

Also, none of the "sls command"s work in a project folder.  Ex. sls print.  
```
Error: "component" input is required to run custom methods
    at Proxy.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:350:13)
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:218:40)
```

**Comment by guilouro** [comment]
@msimonc Did you find some approach to implementing this?

**Comment by msimonc** [comment]
> @msimonc Did you find some approach to implementing this?

sorry @guilouro nothing more at this time

**Comment by guilouro** [comment]
> @msimonc Did you find some approach to implementing this?

I found this article with an interesting approach.

https://codedaily.io/tutorials/Deploy-a-NextJS-App-With-Serverless-to-AWS-Lambda
