### ISSUE TITLE
Unable to generate serverless package

### ISSUE THREAD

**Issue by jlvdh** [serverless-nextjs/serverless-next.js#901]
### Describe the bug
I'm trying to create a package to use as artifact in our AWS CI/CD pipeline. For that I'm running the following command locally: 

`serverless package --component=componentName`

### Actual behavior

I'm getting the following error:

`  Error: Cannot find module '@sls-next/serverless-component@1.19.0-alpha.27'`
### Expected behavior

Generating the package files
### Versions

- OS/Environment: Mac 11.1 / aws
- @sls-next/serverless-component version: 1.19.0-alpha.27
- Next.js version: 10.0.5

### Additional context

full stacktrace:

 ```
  Error: Cannot find module '@sls-next/serverless-component@1.19.0-alpha.27'
Require stack:
- /Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js
- /Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/core/src/index.js
- /Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js
- /Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Template.load (/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js:108:24)
    at async Proxy.<anonymous> (/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:375:19)
    at async Object.runComponents (/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:218:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js',
    '/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/core/src/index.js',
    '/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js',
    '/Users/wokkoubbels/.nvm/versions/node/v14.15.4/lib/node_modules/serverless/bin/serverless.js'
  ]
}
```
### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jonahallibone** [comment]
@jlvdh I don't see `@sls-next/serverless-component@1.19.0-alpha.27` on the [releases page](https://github.com/serverless-nextjs/serverless-next.js/releases)

**Comment by giovai** [comment]
Hello,

Is there any update on this? I'm trying to achieve the same thing with `1.19.0-alpha.43` and getting the same error.

Another thing: is there any way to split build and deploy? There are inputs `build` and `deploy`, but these flags can't be passed from the command line, only through manipulation of the `serverless.yml` file.
