### ISSUE TITLE
Deployments Always Fail ("Throttling: Rate Exceeded")

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#969]
Same symptom as #441. In that thread, it is stated that this issue is due to AWS outage issues, and that nothing can be done by this library. I'm not seeing any issues with AWS, and I've been experiencing this issue for over a week. I'm deploying from Jenkins on EC2. If this persists I'll have no choice but to leave this library.

### Describe the bug
Can't deploy with output "Throttling: Rate exceeded"

### Actual behavior
Can't deploy

### Expected behavior
Can deploy

### Steps to reproduce
Deploy from a CI Pipeline

### Screenshots/Code/Logs
```
  error:
  Throttling: Rate exceeded
    at Request.extractError (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.8/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'Throttling',
  time: 2021-03-25T19:05:39.317Z,
  requestId: 'c7ce9211-4690-45c0-80a3-308b341be8ff',
  statusCode: 400,
  retryable: true
}
```

### Versions
- OS/Environment: Alpine linux
- @sls-next/serverless-component version: 1.19.0-alpha.8
- Next.js version: 9.5.5

### Additional context
- Like the OP in #441, I only have this issue on our CI pipeline; I can deploy from my local (Mac) just fine.
- No changes were made to our project/config prior to seeing this. The only related change would be additional SSG routes, which I don't think should be an issue (<30 pages total).
- This happens every time, not intermittently
- The output does not specify the service throwing the error. I set up a CloudTrail Trail + querying with Athena per [here](https://aws.amazon.com/premiumsupport/knowledge-center/cloudtrail-rate-exceeded) as @danielcondemarin recommends; however it's not giving me any results. I will continue to tweak the query and update if I find more info.

### My intuition
- The fact that this is only reproducible from EC2 seems to implicate IAM / security groups as the throttled service, as mentioned in #441. The AWS status page mentions nothing however.
- Regardless of the cause, it should be possible to implement backoff + retry right? From the call stack, it looks like all associated code is within this project.

Thanks for help with this; this is pretty urgent for us.

**Comment by dphang** [comment]
I haven't seen this issue myself before but wondering if maybe AWS also rate limits based on ip address too? Since in Ci/CD it may use machines with similar IP addresses. If you have many CI pipelines running, maybe that could be the cause?

I think you can also raise a ticket with AWS support and they should be able to raise the limit - I think we had done that for this package's e2e tests since up to 9 were running simultaneously.

I believe the the AWS Node.js clients used in the code normally do exponential backoff retry for any retryable exception, not sure if it is working for throttling errors though. We can certainly check and try to improve that if it is not working as expected.

**Comment by cweekly** [comment]
FWIW, I'm seeing this too, invoking `serverless` from GitLab CI pipeline -- albeit with 1.18.0.

**Comment by dphang** [comment]
@cweekly I was trying to update the AWS retry policy to retry for longer in the latest alpha version, hopefully this doesn't happen as often

**Comment by dphang** [comment]
This should be "fixed" in https://github.com/serverless-nextjs/serverless-next.js/pull/1248 and https://github.com/serverless-nextjs/serverless-next.js/pull/1247. I tried to increase retry policy and also checked that everything is deployed sequentially, so hopefully it should be fairly mitigated. On e2e tests I don't see any rate issues lately, previously we used to get a bunch due to many running at the same time. But if it's still an issue I think there's not much we can do here (but you can by trying to spread out apps across different AWS accounts, regions, if possible or request a rate increase from AWS). At least that is what I do to try to avoid throttling issues.
