### ISSUE TITLE
Error when deploying via Github actions: InvalidLambdaFunctionAssociation: The function cannot have a layer.

### ISSUE THREAD

**Issue by jonthewayne** [serverless-nextjs/serverless-next.js#982]
### Describe the bug
When I try to deploy using github actions, I get this error:

_InvalidLambdaFunctionAssociation: The function cannot have a layer._

### Expected behavior
It should deploy properly. I hadn't noticed that my github actions started failing to deploy using @sls-next/serverless-component@1.17.0 as far back as March 4th. The last successful deploy I have is Feb 22nd. 

As far as I know, I did nothing that could have caused this.

I tried using @sls-next/serverless-component@1.18.0 but it gave the same error. 

### Steps to reproduce
Deploy using github actions. 

### Screenshots/Code/Logs
My github action log:

` error:
  InvalidLambdaFunctionAssociation: The function cannot have a layer. Function: arn:aws:lambda:us-east-1:687033306281:function:12nc4hl-5ihafwq:702
    at Request.extractError (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/aws-sdk/lib/request.js:38:9) {
  code: 'InvalidLambdaFunctionAssociation',
  time: 2021-04-03T08:58:06.779Z,
  requestId: '48c6f42a-7e43-4db3-9d9e-d3233d6e439a',
  statusCode: 400,
  retryable: false,
  retryDelay: 74.63832062838645`

### Versions
- OS/Environment: latest Ubuntu Linux
- @sls-next/serverless-component version: @sls-next/serverless-component@1.18.0
- Next.js version: ^9.4.4

**Comment by jonthewayne** [comment]
Whoops, turns out I had changed something. In the AWS admin I had enabled lambda insights on dev to try and help diagnose something. Turns out that added a lambda layer which doesn’t work when connecting lambda@edge to cloudfront.

**Comment by ka8725** [comment]
> Turns out that added a lambda layer which doesn’t work when connecting lambda@edge to cloudfront.

@jonthewayne thanks for sharing that and sorry to bother you. Have you found a workaround for that? If not layers, then what can work? I need Crypto lib installed for a python function.

**Comment by jonthewayne** [comment]
Sorry man, I haven't found a workaround for attaching layers to a lambda@edge function. To be fair though, I haven't tried recently, so something could have changed since then. Good luck!
