### ISSUE TITLE
Serverless AWS error: AccessDenied: Access Denied (enableS3Acceleration: false)

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [serverless-nextjs/serverless-next.js#988]
```sh
$ npx create-next-app .
$ npx serverless create --template aws-nodejs
```

serverless.yml:
```yml
myDemoApp:
  component: "@sls-next/serverless-component"
  inputs:
    enableS3Acceleration: false
```

```sh
$ npx serverless --debug
```

ERROR:

```sh

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Collecting page data...
info  - Generating static pages (0/3)
info  - Generating static pages (3/3)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          3.46 kB          67 kB
├   └ css/9c4381274c2a4fd9d205.css                             669 B
├   /_app                                                      0 B            63.5 kB
├ ○ /404                                                       3.46 kB          67 kB
└ λ /api/hello                                                 0 B            63.5 kB
+ First Load JS shared by all                                  63.5 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.4a765b.js  13.4 kB
  ├ chunks/framework.4b1bec.js                                 41.8 kB
  ├ chunks/main.e3cfaf.js                                      7.12 kB
  ├ chunks/pages/_app.fce667.js                                529 B
  ├ chunks/webpack.50bee0.js                                   751 B
  └ css/381f5b9c92d1673af027.css                               203 B

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

  DEBUG ─ Deploying bucket 5fs342-6gd7zfk in region us-east-1.
  DEBUG ─ Checking if bucket 5fs342-6gd7zfk exists.
  DEBUG ─ Bucket 5fs342-6gd7zfk does not exist. Creating...
  DEBUG ─ Bucket 5fs342-6gd7zfk created. Confirming it's ready...
  DEBUG ─ Bucket 5fs342-6gd7zfk creation confirmed.
  DEBUG ─ Setting acceleration to "true" for bucket 5fs342-6gd7zfk.

  error:
  AccessDenied: Access Denied
    at Request.extractError (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\services\s3.js:71
8:35)
    at Request.callListeners (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\sequential_execu
tor.js:106:20)
    at Request.emit (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\sequential_executor.js:78
:10)
    at Request.emit (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\state_machi
ne.js:14:12)
    at C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\me\.serverless\components\registry\npm\@sls-next\serverless-component@1.17.0\node_modules\aws-sdk\lib\sequential_execu
tor.js:116:18) {
  code: 'AccessDenied',
  region: null,
  time: 2021-04-11T04:35:06.221Z,
  requestId: '1M7C2SYVYC0R75EY',
  extendedRequestId: '9Iy9eUfrax7cWTOFv5PCYd/hjZKlhecjpSKX8Y+zOpC3NdQo1sPSzOnjjVQGQaN1dAiD8xrlo30=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 91.23101770197289
}

  11s » myDemoApp » AccessDenied: Access Denied
```

**Comment by raffij** [comment]
Looks like you are using an old version 1.17.0? We've been using the latest alpha versions in production and had no issue. You could try upgrading to the latest.

However if this is a permissions issue then I'd check the section "AWS Permissions for deployment" in the readme to make sure all the permissions you need are set.

**Comment by MaxmaxmaximusAWS** [comment]
it turned out that acceleration is not available for my account, but I disable it, and disabling does not work, should disabling work in alpha versions?

**Comment by lucas-brito** [comment]
I just had the same issue, `enableS3Acceleration: false` does not work in the last stable version use the last alpha instead

Just change from `component: "@sls-next/serverless-component"` to  `component: "@sls-next/serverless-component@1.19.0-alpha.45"` and it should work

**Comment by dphang** [comment]
Yes, it should be in the later versions. Please always try latest alpha version if a feature is mentioned in the README but doesn't work, as the README may reflect new changes that may not be in stable versions (or alpha, but I do try to keep alpha publishes up-to-date with master as much as possible). I'll close this now, please open a new issue if there are other issues.
