### ISSUE TITLE
Using webpack 5 causes 503

### ISSUE THREAD

**Issue by darren-charterindex** [serverless-nextjs/serverless-next.js#991]
Using webpack 5, returns the following from Cloudfront:

```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

Using versions:

```
@sls-next/serverless-component@1.19.0-alpha.43
"next": "^10.1.3",
```

**Comment by dphang** [comment]
Please post more info such as the actual logs you are seeing in the Lambda@Edge.

**Comment by darren-charterindex** [comment]
Will do shortly 👍

**Comment by darren-charterindex** [comment]
No logs from the Lambda, the error is from CloudFront. No further logs from CloudFront.

The app runs as prod locally correctly using webpack 5, and works correctly in the Lambda using webpack 4. There is no difference except:

```
future: {
  webpack5: true,
},
```

**Comment by dphang** [comment]
I see, are there no logs in the CloudWatch region you are accessing from? Usually 503 means there is some problem with the Lambda function itself, so it should show the exception if any.

In any case I can try to look at it later in the week

**Comment by jordie23** [comment]
Can confirm I get the same. The lambda function is not being executed.

This is only happening for our API paths though.

**Comment by darren-charterindex** [comment]
That is correct. No relevant Cloudfront logs, either in us-east-1 or locally in eu-west-2.

**Comment by damanptyltd** [comment]
> +1, happened after upgarde of `next.js` from `10.2.0` to `10.2.1`, using webpack 5. Downgrading `next.js` solves the issue.
> 
> ```
> "@sls-next/serverless-component": "1.19.0"
> ```

Same issue with `10.2.2`.

**Comment by dphang** [comment]
We fixed some 503 issues due to chunks not being copied in: https://github.com/serverless-nextjs/serverless-next.js/commit/f04fe3419915fddb2c1c898922ade859b42acbcb, wondering if it is related and this issue still occurs in the latest? (sorry, personally haven't been following all the latest incremental versions from 10.1 -> 10.2 too closely, so not sure about the webpack transition to webpack 5)?

**Comment by talaikis** [comment]
Same for `10.2.3`

**Comment by dphang** [comment]
Thanks, can someone please post a sample repro repo with the latest 10.2.3 and latest alpha version of this component (1.20.0-alpha.20). It's not reproducing for me in the test e2e apps in this repo (next-app). I am not sure what configuration is causing it... until there is a reproduction, I'm afraid I won't be able to dig further.

**Comment by talaikis** [comment]
Ok, here's reproduction, I didn't even added next.config.js. The problem is that latest alpha version *works*, but for pages/*.js, it *does not* for pages/subfolder/*.js

Repo: `https://github.com/talaikis/serverless-repro`

Visit deployed page: `https://d86v7ththghx1.cloudfront.net/test/test?id=test`

**Comment by dphang** [comment]
@talaikis thanks, I just tested your repro, it doesn't have any 503s for me. I'm deploying from Mac Big Sur (11.2.3) if it makes a difference.

See link: https://d1kp2dv65i9yj1.cloudfront.net/test/test?id=121234343

Any more info like OS, CloudWatch logs you could post?

**Comment by talaikis** [comment]
Yeah, I'm on Windows 10.

Log error:

```
Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module './pages/test/test.js'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module './pages/test/test.js'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:730:27)",
        "    at Module.require (internal/modules/cjs/loader.js:957:19)",
        "    at require (internal/modules/cjs/helpers.js:88:18)",
        "    at /var/task/index.js:1:22738",
        "    at re (/var/task/index.js:1:18020)",
        "    at ne (/var/task/index.js:1:18827)",
        "    at async ye (/var/task/index.js:1:22672)",
        "    at async Runtime.exports.handler (/var/task/index.js:1:29005)"
    ]
}
```

It seems that page is not built into `.serverless_nextjs`

**Comment by dphang** [comment]
Cool, so please post what `.next` and `.serverless_nextjs` directories look like, does it have the nested pages correctly e.g `.next/serverless/pages/test/test.js`? I believe we should just copy the JS pages as-is from `.next` (filtering HTML and unneeded JS files), the logic is here: https://github.com/serverless-nextjs/serverless-next.js/blob/8c25eea6c918bddaf3c62d78424e2d7732441df2/packages/libs/lambda-at-edge/src/build.ts#L288-L308, no special logic on Windows.

**Comment by talaikis** [comment]
> Cool, so please post what `.next` and `.serverless_nextjs` directories look like, does `.next` have the nested pages correctly e.g 

Repo has those, `.serverless_nextjs` is empty for all edge lambda subfolders:
https://github.com/talaikis/serverless-repro/tree/master/.serverless_nextjs/default-lambda/pages

`.next` has everything:
https://github.com/talaikis/serverless-repro/tree/master/.next/serverless/pages/test

**Comment by dphang** [comment]
OK, I think I know what the problem is, might be that windows is using backslashes in paths, whereas in here we might exclude it due to this logic: https://github.com/serverless-nextjs/serverless-next.js/blob/f7f780bf99078d3a7056ce2ad2a4c734a4782d50/packages/libs/lambda-at-edge/src/build.ts#L164-L167.

We need to be more careful with always using posix paths when doing comparisons... and we definitely need to start adding e2e tests for windows soon, will prioritize for 1.20 release...

**Comment by talaikis** [comment]
> OK, I think I know what the problem is, might be that windows is using backslashes in paths, whereas in here we might exclude it due to this logic, if it is nested then I think there is backslash and it fails the condition, so it gets excluded:

it's possible, better o use `relativePageFile.startsWith(path.sep)`

**Comment by dphang** [comment]
The fix has been published in the latest alpha version, please try and let me know if it works?
