### ISSUE TITLE
Undescribed Error

### ISSUE THREAD

**Issue by msaraac** [serverless-nextjs/serverless-next.js#996]
I'm getting this error . Anyone understands this ?

```
 TypeError: Unexpected MODIFIER at 21, expected END
    at mustConsume (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/path-to-regexp/dist/index.js:114:15)
    at parse (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/path-to-regexp/dist/index.js:173:9)
    at stringToRegexp (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/path-to-regexp/dist/index.js:331:27)
    at Object.pathToRegexp (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/path-to-regexp/dist/index.js:405:12)
    at Object.exports.default (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/@sls-next/lambda-at-edge/dist/lib/pathToRegexStr.js:4:46)
    at /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/@sls-next/lambda-at-edge/dist/build.js:282:56
    at Array.forEach (<anonymous>)
    at Builder.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/@sls-next/lambda-at-edge/dist/build.js:251:43)
    at Generator.next (<anonymous>)
    at fulfilled (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.3/node_modules/@sls-next/lambda-at-edge/dist/build.js:5:58)
[G[?25h[G[J
  54s › tkApplication › TypeError: Unexpected MODIFIER at 21, expected END
```

**Comment by dphang** [comment]
Most likely some page path you have has a special character that couldn't be parsed by `pathToRegexp` library during the build step (which generates all the route and page manifests). Agree the error could be more descriptive - probably could add the path it failed to parse.
